/* Dawami 10.0 — source mirror of the inlined GitHub Pages app */
(function(){
"use strict";
var C=window.DawamiCore,KEY="dawami-data-v3",BACKUP="dawami-v3-legacy-backup";
var DEFAULT_COLORS={accent:"#3B82F6",work:"#F6C453",off:"#64748B",extra:"#FF8A4C",annual:"#58C7E3",sick:"#ED6F7D",training:"#36B594",official:"#9B6CF2"};
var PALETTES={
 gold:{accent:"#3B82F6",work:"#F6C453",off:"#64748B",extra:"#FF8A4C",annual:"#58C7E3",sick:"#ED6F7D",training:"#36B594",official:"#9B6CF2"},
 ocean:{accent:"#2585D9",work:"#55BDEB",off:"#4E7185",extra:"#F59E5B",annual:"#38BDF8",sick:"#F4728A",training:"#34D399",official:"#8B7CF6"},
 mint:{accent:"#18A879",work:"#52C99B",off:"#5B746B",extra:"#F59E5B",annual:"#4CB8D4",sick:"#EC7A86",training:"#2DB486",official:"#8A74D6"},
 coral:{accent:"#F26A4B",work:"#FF9376",off:"#82645E",extra:"#FFA34F",annual:"#5CBFDB",sick:"#E85C6A",training:"#43B99A",official:"#9A70DB"},
 violet:{accent:"#7C5CE4",work:"#AD91F7",off:"#716987",extra:"#FF9860",annual:"#5BC0DE",sick:"#EC708C",training:"#49B99D",official:"#8F61E9"}
};
var data=loadData(),S=data.schedule,tz=data.settings.timezone||"Asia/Muscat",today=C.dateKeyAt(Date.now(),tz),month=today.slice(0,7)+"-01",page="home",selectedDay=today,setupPattern="14-14",setupStep=1,timerTarget=null,notifyTimers=[],holidayStore=read("dawami-oman-holidays-v3")||{years:{}},holidayLoading={},calendarView=data.settings.calendarView||"month",selectedDates=new Set(),undoStack=[],dayClipboard=null,installPrompt=null,compareSchedule=null;
var months=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];



function $(q,r){return(r||document).querySelector(q)}
function $$(q,r){return Array.prototype.slice.call((r||document).querySelectorAll(q))}
function copy(x){return JSON.parse(JSON.stringify(x))}
function read(k){try{var v=localStorage.getItem(k);return v?JSON.parse(v):null}catch(e){return null}}
function defaults(){return{version:5,onboarded:false,profile:{name:""},settings:{timezone:"Asia/Muscat",theme:"dark",dayStart:"07:00",dayEnd:"19:00",nightStart:"19:00",nightEnd:"07:00",notificationEnabled:false,reminderBefore:60,notifyOptions:{nightBefore:false,return24:false,nightShift:false},colorTheme:"gold",colors:copy(DEFAULT_COLORS),annualBalance:30,carryOver:0,deductRest:false,calendarView:"month",scheduleLocked:false,customCycleText:"",pay:{enabled:false,basic:0,basicHours:160,overtimeMultiplier:1.5,nightAllowance:0,siteAllowance:0,payDay:25}},schedule:{anchor:C.dateKeyAt(Date.now(),"Asia/Muscat"),patternId:"14-14",patternName:"14 يوم دوام / 14 يوم راحة",cycle:copy(C.presets()["14-14"].cycle),overrides:{},leaves:[]},migratedFrom:[]}}
function normalize(d){var base=defaults(),savedSettings=d.settings||{},savedColors=savedSettings.colors;d.version=5;d.profile=Object.assign(base.profile,d.profile||{});d.settings=Object.assign(base.settings,savedSettings);d.settings.colors=Object.assign(copy(DEFAULT_COLORS),savedColors||(PALETTES[savedSettings.colorTheme]||{}));d.settings.notifyOptions=Object.assign(base.settings.notifyOptions,savedSettings.notifyOptions||{});d.settings.pay=Object.assign(base.settings.pay,savedSettings.pay||{});d.schedule=Object.assign(base.schedule,d.schedule||{});d.schedule.cycle=d.schedule.cycle&&d.schedule.cycle.length?d.schedule.cycle:base.schedule.cycle;d.schedule.overrides=d.schedule.overrides||{};d.schedule.leaves=Array.isArray(d.schedule.leaves)?d.schedule.leaves:[];d.migratedFrom=d.migratedFrom||[];return d}
function loadData(){
 var current=read(KEY);if(current&&current.schedule)return normalize(current);
 var d=defaults(),oldP=read("dawami-cycle-prefs")||read("dawami-github-prefs"),oldO=read("dawami-cycle-overrides")||{},oldS=read("dawami-github-schedule");
 if(oldP||oldS||Object.keys(oldO).length){
  if(!localStorage.getItem(BACKUP))try{localStorage.setItem(BACKUP,JSON.stringify({savedAt:new Date().toISOString(),prefs:oldP,changes:oldO,schedule:oldS}))}catch(e){}
  var p=oldP||{},on=Number(p.onDays||p.workDays||14),off=Number(p.offDays||p.restDays||14),work={type:"day",label:"دوام",start:p.shiftStart||"07:00",end:p.shiftEnd||"19:00"};
  d.schedule.anchor=p.anchor||p.startDate||d.schedule.anchor;d.schedule.cycle=C.repeat(work,on).concat(C.repeat({type:"off",label:"إجازة"},off));if(p.anchorPhase==="off")d.schedule.cycle=C.repeat({type:"off",label:"إجازة"},off).concat(C.repeat(work,on));
  d.schedule.patternId=on+"-"+off;d.schedule.patternName=on+" يوم دوام / "+off+" يوم إجازة";d.settings.theme=p.theme||"dark";d.settings.dayStart=work.start;d.settings.dayEnd=work.end;d.profile.name=p.name||"";d.onboarded=true;
  Object.keys(oldO).forEach(function(k){var v=oldO[k];d.schedule.overrides[k]=v==="off"?{type:"off",label:"إجازة"}:v==="work"?copy(work):v});
  var list=Array.isArray(oldS)?oldS:(oldS&&(oldS.days||oldS.entries||oldS.schedule));if(Array.isArray(list))list.forEach(function(x){if(x&&x.date)d.schedule.overrides[x.date.slice(0,10)]={type:mapType(x.type||x.status),label:x.label,start:x.start||x.startTime,end:x.end||x.endTime,note:x.note||""}});
  d.migratedFrom=["النسخة السابقة"];
 }
 d=normalize(d);try{localStorage.setItem(KEY,JSON.stringify(d))}catch(e){}return d
}
function save(msg){try{localStorage.setItem(KEY,JSON.stringify(data));if(msg)toast(msg)}catch(e){toast("ما قدرت أحفظ البيانات")}}
function mapType(v){v=String(v||"").toLowerCase();if(/night|ليل/.test(v))return"night";if(/off|rest|راح|إجاز|اجاز/.test(v))return"off";return"day"}
function add(k,n){return C.addDays(k,n)}
function parts(k){return C.monthKeyParts(k)}
function fmtKey(k,o){if(!k)return"—";return new Intl.DateTimeFormat("ar-OM",Object.assign({timeZone:"UTC",day:"numeric",month:"short"},o||{})).format(new Date(k+"T12:00:00Z"))}
function fmtTime(ms,o){if(!ms)return"—";return new Intl.DateTimeFormat("ar-OM",Object.assign({timeZone:tz,weekday:"long",day:"numeric",month:"long",hour:"numeric",minute:"2-digit"},o||{})).format(new Date(ms))}
function pad(n){return String(Math.max(0,n)).padStart(2,"0")}
function remaining(ms){var m=Math.max(0,Math.floor(ms/60000)),d=Math.floor(m/1440),h=Math.floor((m%1440)/60);return pad(d)+" يوم : "+pad(h)+" ساعة : "+pad(m%60)+" دقيقة"}
function esc(v){return String(v||"").replace(/[&<>"]/g,function(x){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[x]})}
function holidayName(h){var n=String((h&&(h.localName||h.name))||"عطلة رسمية"),e=String((h&&h.name)||n).toLowerCase();if(/[\u0600-\u06ff]/.test(n))return n;if(/fitr/.test(e))return"عيد الفطر";if(/adha/.test(e))return"عيد الأضحى";if(/prophet|mawlid/.test(e))return"المولد النبوي";if(/islamic new year|hijri/.test(e))return"رأس السنة الهجرية";if(/national day/.test(e))return"العيد الوطني";if(/accession|renaissance/.test(e))return"يوم تولّي السلطان";if(/ascension|isra/.test(e))return"الإسراء والمعراج";return n}
function holidayFor(k){var y=holidayStore.years&&holidayStore.years[k.slice(0,4)],list=y&&(y.items||y);return Array.isArray(list)?list.find(function(x){return x.date===k}):null}
async function ensureHolidays(year){var key=String(year),saved=holidayStore.years&&holidayStore.years[key],fresh=saved&&saved.fetchedAt&&Date.now()-saved.fetchedAt<86400000;if(fresh||holidayLoading[key])return;holidayLoading[key]=true;var sync=$("#holidaySync");if(sync)sync.textContent="جاري تحديث عطلات سلطنة عُمان…";try{var url="holidays-om.json?build=20260828-2253",local=await fetch(url,{cache:"reload"});if(!local.ok)throw new Error("holiday file");var bundle=await local.json(),list=bundle.years&&bundle.years[key];if(!Array.isArray(list)||!list.length)throw new Error("holiday year");holidayStore.years=holidayStore.years||{};holidayStore.years[key]={fetchedAt:Date.now(),items:list.map(function(x){return{date:x.date,name:x.name||"",localName:x.localName||""}})};localStorage.setItem("dawami-oman-holidays-v3",JSON.stringify(holidayStore));if(sync)sync.textContent="العطلات الرسمية محدثة • الهجرية حسب الإعلان الرسمي";renderCalendar();renderHome()}catch(e){if(sync)sync.textContent=saved?"نعرض آخر نسخة محفوظة من العطلات":"ستظهر العطلات تلقائيًا عند توفر الاتصال"}finally{delete holidayLoading[key]}}
function textFor(e){if(!e)return"إجازة";var t=e.type;if(t==="night")return"دوام ليلي";if(t==="off")return"إجازة";if(t==="annual")return"إجازة سنوية";if(t==="leave"||t==="comp"||t==="unpaid"||t==="emergency")return"إجازة مسجلة";if(t==="sick")return"مرضية";if(t==="training")return"تدريب";if(t==="overtime")return"إكسترا دي";return"دوام"}
function classFor(e){if(!e)return"off";if(e.type==="night")return"night";if(e.type==="off")return"off";if(e.type==="overtime")return"extra";if(e.type==="training")return"training";if(e.type==="sick")return"sick";if(["annual","leave","comp","unpaid","emergency"].indexOf(e.type)>=0)return"leave";return"work"}
function lastWork(k){for(var i=1;i<500;i++){var d=add(k,-i),ev=C.eventsForDate(S,d).filter(C.isWork);if(ev.length){var e=ev[ev.length-1];return C.interval(d,e,tz)}}return null}
function exactBlock(block){if(!block)return null;var before=lastWork(block.start),next=C.nextShift(S,C.zonedEpoch(block.returnDate,"00:00",tz),tz);return{start:before?before.end:C.zonedEpoch(block.start,"00:00",tz),end:next?next.start:C.zonedEpoch(add(block.end,1),"00:00",tz),next:next}}
function toast(msg){var e=$("#toast");e.textContent=msg;e.classList.add("show");clearTimeout(e._t);e._t=setTimeout(function(){e.classList.remove("show")},1800)}
function open(id){var modal=$("#"+id);modal.classList.add("open");document.body.classList.add("modal-open");var sheet=$(".sheet",modal);if(sheet){sheet.style.transform="";sheet.classList.remove("dragging","settling")}if(id!=="setupModal"&&!(history.state&&history.state.dawamiModal===id))history.pushState({dawamiPage:page,dawamiModal:id},"",location.pathname+location.search+"#"+page+"/"+id)}
function close(id,fromHistory){$("#"+id).classList.remove("open");if(!$(".modal.open"))document.body.classList.remove("modal-open");if(!fromHistory&&history.state&&history.state.dawamiModal===id)history.back()}

function applyPalette(){var colors=Object.assign(copy(DEFAULT_COLORS),data.settings.colors||{}),root=document.documentElement;data.settings.colors=colors;Object.keys(colors).forEach(function(k){root.style.setProperty("--"+(k==="off"?"off":k)+"-color",colors[k])});root.style.setProperty("--accent",colors.accent);root.style.setProperty("--yellow",colors.work);root.style.setProperty("--black",colors.off)}
function renderAll(){S=data.schedule;tz=data.settings.timezone||"Asia/Muscat";today=C.dateKeyAt(Date.now(),tz);calendarView=data.settings.calendarView||calendarView||"month";document.documentElement.dataset.theme=data.settings.theme;applyPalette();var meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=data.settings.theme==="dark"?"#070A10":"#F3F6FA";$("#themeBtn").classList.toggle("moon",data.settings.theme!=="dark");$("#themeBtn").setAttribute("aria-label",data.settings.theme==="dark"?"تشغيل الوضع الفاتح":"تشغيل الوضع الداكن");renderHome();renderCalendar();renderSettings();renderAdvanced()}
function renderHome(){
 var now=Date.now(),state=C.nowStatus(S,now,tz),currentRest=state.kind==="off"||state.kind==="leave",upcomingFrom=currentRest&&state.nextShift?state.nextShift.date:today,block=C.restBlock(S,upcomingFrom,false),exact=exactBlock(block),card=$("#statusCard"),cyclePos=((C.diffDays(S.anchor,today)%S.cycle.length)+S.cycle.length)%S.cycle.length+1;
 card.className="status "+(state.kind==="work"?"work":state.kind==="upcoming"?"soon":"off");
 if(state.kind==="work"){$("#statusTitle").textContent="أنت في الدوام الآن";$("#statusSub").textContent=textFor(state.event)+" من "+state.event.start+" إلى "+state.event.end;$("#countLabel").textContent="باقي على الإجازة القادمة";timerTarget=exact&&exact.start}
 else if(state.kind==="leave"){$("#statusTitle").textContent="أنت في إجازة مسجلة";$("#statusSub").textContent="استمتع بوقتك، نخبرك متى ترجع";$("#countLabel").textContent="باقي على الرجوع للدوام";timerTarget=state.nextShift&&state.nextShift.start}
 else if(state.kind==="off"){$("#statusTitle").textContent="أنت في يوم راحة";$("#statusSub").textContent="دوامك القادم محسوب وجاهز";$("#countLabel").textContent="باقي على الرجوع للدوام";timerTarget=state.nextShift&&state.nextShift.start}
 else{$("#statusTitle").textContent="دوامك يبدأ بعد…";$("#statusSub").textContent=textFor(state.nextShift&&state.nextShift.event)+" الساعة "+((state.nextShift&&state.nextShift.event.start)||"—");$("#countLabel").textContent="باقي على بداية الدوام";timerTarget=state.nextShift&&state.nextShift.start}
 $("#cycleDay").textContent=cyclePos;$("#cycleLength").textContent="من "+S.cycle.length+" يوم";$("#cycleRing").style.setProperty("--p",(cyclePos/S.cycle.length*100)+"%");
 var workLeft=block?C.workDaysBetween(S,today,block.start):0;$("#daysToLeave").textContent=block?workLeft+" يوم":"—";$("#leaveHint").textContent=block?"دوام متبقٍ فعليًا":"أضف إجازة أو اضبط جدولك";
 $("#leaveStartShort").textContent=exact?new Intl.DateTimeFormat("ar-OM",{timeZone:tz,day:"numeric",month:"short"}).format(new Date(exact.start)):"—";$("#leaveStartFull").textContent=exact?fmtTime(exact.start,{weekday:"long",hour:"numeric",minute:"2-digit"}):"—";
 $("#returnShort").textContent=exact&&exact.next?new Intl.DateTimeFormat("ar-OM",{timeZone:tz,day:"numeric",month:"short"}).format(new Date(exact.next.start)):"—";$("#returnFull").textContent=exact&&exact.next?fmtTime(exact.next.start,{weekday:"long",hour:"numeric",minute:"2-digit"}):"—";
 var tp=parts(today),monthly=C.monthStats(S,tp.year,tp.month),balance=annualRemainingValue(tp.year),next=state.nextShift;
 $("#monthWorkDays").textContent=monthly.workDays+" يوم";$("#monthWorkHint").textContent=months[tp.month-1]+" • محسوب من جدولك";$("#monthRestDays").textContent=monthly.offDays+" يوم";$("#monthHours").textContent=Math.round(monthly.hours)+" ساعة";$("#monthOvertime").textContent=monthly.overtimeHours?Math.round(monthly.overtimeHours)+" ساعة إضافي":"بدون إضافي";$("#annualHome").textContent=balance+" يوم";
 $("#nextShiftShort").textContent=next?fmtKey(next.date,{day:"numeric",month:"short"}):"—";$("#nextShiftFull").textContent=next?textFor(next.event)+" • "+next.event.start:"ما فيه دوام قادم";
 renderCountdown();var strip=$("#nextStrip");strip.innerHTML="";for(var i=0;i<10;i++){var k=add(today,i),events=C.eventsForDate(S,k),e=C.primaryEvent(S,k),holiday=holidayFor(k),b=document.createElement("button");b.className="strip-day "+classFor(e)+(i===0?" today":"")+(holiday?" official":"");b.innerHTML="<small>"+(i===0?"اليوم":i===1?"بكرة":fmtKey(k,{weekday:"short"}))+"</small><b>"+Number(k.slice(8))+"</b><span>"+events.map(textFor).join(" + ")+"</span>"+(holiday?'<small class="official-name">'+esc(holidayName(holiday))+"</small>":"");b.onclick=(function(x){return function(){showDay(x)}})(k);strip.appendChild(b)}ensureHolidays(Number(today.slice(0,4)))
}
function renderCountdown(){var box=$("#countdown");if(timerTarget){var m=Math.max(0,Math.floor((timerTarget-Date.now())/60000)),d=Math.floor(m/1440),hr=Math.floor((m%1440)/60),min=m%60;box.className="countdown-parts";box.innerHTML="<span><b>"+pad(d)+"</b><small>يوم</small></span><i>:</i><span><b>"+pad(hr)+"</b><small>ساعة</small></span><i>:</i><span><b>"+pad(min)+"</b><small>دقيقة</small></span>"}else{box.className="countdown-parts empty";box.textContent="ما فيه موعد قريب"}if(timerTarget&&Date.now()>timerTarget)renderHome()}
function renderCalendar(){
 var p=parts(month),surface=$("#calendarSurface"),grid=$("#calendarGrid"),dates=[],first=p.year+"-"+String(p.month).padStart(2,"0")+"-01";$("#monthLabel").textContent=months[p.month-1]+" "+p.year;surface.className="calendar-surface view-"+calendarView;$$("[data-calendar-view]").forEach(function(b){b.classList.toggle("active",b.dataset.calendarView===calendarView)});
 if(calendarView==="month"){var offset=(new Date(first+"T12:00:00Z").getUTCDay()+6)%7,start=add(first,-offset);for(var i=0;i<42;i++)dates.push(add(start,i))}
 else if(calendarView==="week"){var focus=selectedDay&&selectedDay.slice(0,7)===month.slice(0,7)?selectedDay:first,dow=(new Date(focus+"T12:00:00Z").getUTCDay()+6)%7,ws=add(focus,-dow);for(var w=0;w<7;w++)dates.push(add(ws,w))}
 else{for(var d=1;d<=C.daysInMonth(p.year,p.month);d++)dates.push(p.year+"-"+String(p.month).padStart(2,"0")+"-"+String(d).padStart(2,"0"))}
 grid.className="calendar-grid calendar "+(calendarView==="list"?"view-list":"view-"+calendarView);grid.innerHTML="";
 dates.forEach(function(k){var events=C.eventsForDate(S,k),e=C.primaryEvent(S,k),holiday=holidayFor(k),b=document.createElement("button"),outside=parts(k).month!==p.month,labels=events.map(textFor),meta=events.filter(C.isWork).map(function(x){return(x.start||"")+"–"+(x.end||"")}).join(" • ");b.className="day "+classFor(e)+(outside?" out":"")+(k===today?" today":"")+(S.overrides[k]!==undefined?" manual":"")+(events.some(function(x){return x.note})?" has-note":"")+(holiday?" official":"")+(selectedDates.has(k)?" selected":"")+(calendarView==="list"?" list-day":"");b.dataset.date=k;
 b.innerHTML="<em>"+(calendarView==="list"?fmtKey(k,{weekday:"short",day:"numeric"}):Number(k.slice(8)))+"</em><b>"+labels.join(" + ")+"</b>"+(calendarView==="list"?'<span class="list-meta">'+esc(meta||"بدون وقت")+"</span>":"")+(holiday?'<small class="official-name">'+esc(holidayName(holiday))+"</small>":"");bindCalendarDay(b,k);grid.appendChild(b)});
 updateSelectionBar();ensureHolidays(p.year)
}
function showDay(k){selectedDay=k;var events=C.eventsForDate(S,k),e=events[0]||{type:"off"},holiday=holidayFor(k),special=["overtime","annual","sick","training"],bits=[];$("#selectedDate").textContent=fmtKey(k,{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("#selectedStatus").textContent=(holiday?holidayName(holiday)+" • ":"")+events.map(textFor).join("، ");if(holiday)bits.push("عطلة رسمية في سلطنة عُمان");events.forEach(function(x){if(C.isWork(x)&&x.start&&x.end)bits.push(textFor(x)+" من "+x.start+" إلى "+x.end)});if(e.job)bits.push("الجوب: "+e.job);if(e.location)bits.push("الموقع: "+e.location);if(e.note)bits.push(e.note);$("#selectedTime").textContent=bits.join(" • ")||"ما عندك إضافة على هذا اليوم";$("#dayType").value=special.indexOf(e.type)>=0?e.type:"overtime";$("#dayStart").value=e.start||data.settings.dayStart;$("#dayEnd").value=e.end||data.settings.dayEnd;$("#dayLocation").value=e.location||"";$("#dayJob").value=e.job||"";$("#dayNote").value=e.note||"";$("#dayAppend").checked=false;selectDayType($("#dayType").value);$("#toggleEditDay").textContent=S.overrides[k]!==undefined?"تعديل أو إضافة":"أضف على هذا اليوم";$("#toggleEditDay").disabled=!!data.settings.scheduleLocked;$("#toggleEditDay").textContent=data.settings.scheduleLocked?"الجدول مقفول":$("#toggleEditDay").textContent;$("#editDay").hidden=true;open("dayModal")}
function selectDayType(type){$("#dayType").value=type;var timed=type==="overtime"||type==="training";$("#dayTimes").hidden=!timed;if(timed&&!$("#dayStart").value){$("#dayStart").value=data.settings.dayStart;$("#dayEnd").value=data.settings.dayEnd}$$("[data-day-type]").forEach(function(b){b.classList.toggle("active",b.dataset.dayType===type)})}
function moveMonth(n){var p=parts(month),d=new Date(Date.UTC(p.year,p.month-1+n,1)),grid=$("#calendarGrid");month=d.getUTCFullYear()+"-"+String(d.getUTCMonth()+1).padStart(2,"0")+"-01";renderCalendar();grid.classList.remove("month-next","month-prev");void grid.offsetWidth;grid.classList.add(n>0?"month-next":"month-prev");setTimeout(function(){grid.classList.remove("month-next","month-prev")},300);pulse(5)}
function reminderLabel(min){min=Number(min)||60;if(min===30)return"30 دقيقة";if(min===60)return"ساعة";if(min===120)return"ساعتين";if(min===720)return"12 ساعة";if(min===1440)return"يوم";return min+" دقيقة"}
function renderSettings(){
 var id=C.presets()[S.patternId]?S.patternId:(S.patternId==="custom"?"custom":"14-14"),opt=data.settings.notifyOptions||{},pay=data.settings.pay||{};$("#settingsName").value=data.profile.name||"";$("#timezoneSelect").value=data.settings.timezone||"Asia/Muscat";$("#reminderBefore").value=String(data.settings.reminderBefore||60);$("#patternSelect").value=id;$("#anchorDate").value=S.anchor;$("#customCycleSettings").hidden=id!=="custom";$("#customCycleText").value=data.settings.customCycleText||"";$("#workStart").value=data.settings.dayStart;$("#workEnd").value=data.settings.dayEnd;$("#nightStart").value=data.settings.nightStart;$("#nightEnd").value=data.settings.nightEnd;$("#nightTimes").hidden=id!=="2d2n4"&&!(S.cycle||[]).some(function(e){return C.normalizeEvent(e).type==="night"});toggleSwitch("darkSwitch",data.settings.theme==="dark");toggleSwitch("notifySwitch",data.settings.notificationEnabled);$("#notifyText").textContent=data.settings.notificationEnabled?"مفعل قبل الدوام بـ"+reminderLabel(data.settings.reminderBefore):"غير مفعل";$("#reminderBefore").disabled=!data.settings.notificationEnabled;$("#notifyNightBefore").checked=!!opt.nightBefore;$("#notifyReturn24").checked=!!opt.return24;$("#notifyNightShift").checked=!!opt.nightShift;
 $("#annualBalance").value=data.settings.annualBalance;$("#carryOver").value=data.settings.carryOver;$("#deductRest").checked=!!data.settings.deductRest;$("#payEnabled").checked=!!pay.enabled;$("#payBasic").value=pay.basic||0;$("#payBasicHours").value=pay.basicHours||160;$("#payOvertimeMultiplier").value=pay.overtimeMultiplier||1.5;$("#payNightAllowance").value=pay.nightAllowance||0;$("#paySiteAllowance").value=pay.siteAllowance||0;$("#payDay").value=pay.payDay||25;$("#payFields").hidden=!pay.enabled;
 document.querySelectorAll("[data-palette]").forEach(function(b){var active=b.dataset.palette===(data.settings.colorTheme||"gold");b.classList.toggle("active",active);b.setAttribute("aria-pressed",active?"true":"false")});document.querySelectorAll("[data-color-key]").forEach(function(input){input.value=(data.settings.colors&&data.settings.colors[input.dataset.colorKey])||DEFAULT_COLORS[input.dataset.colorKey]});renderCyclePreview()
}
function renderCyclePreview(){var box=$("#cyclePreview");box.innerHTML=S.cycle.map(function(e){return'<i class="'+classFor(C.normalizeEvent(e))+'"></i>'}).join("")}
function toggleSwitch(id,on){$("#"+id).classList.toggle("on",!!on)}
function applyTimes(cycle){return cycle.map(function(e){e=copy(e);if(e.type==="day"||e.type==="work"){e.label="دوام";e.start=data.settings.dayStart;e.end=data.settings.dayEnd}if(e.type==="night"){e.label="دوام ليلي";e.start=data.settings.nightStart;e.end=data.settings.nightEnd}if(e.type==="off")e.label="إجازة";return e})}
function patternName(id){var names={"14-14":"14 يوم دوام / 14 يوم راحة","28-14":"28 يوم دوام / 14 يوم راحة","7-7":"7 أيام دوام / 7 أيام راحة","4-4":"4 أيام دوام / 4 أيام راحة","2d2n4":"يومان نهاري / يومان ليلي / 4 أيام راحة","5-2":"5 أيام دوام / يومان راحة",custom:"نمط مخصص"};return names[id]||names["14-14"]}
function savePattern(){var id=$("#patternSelect").value,anchor=$("#anchorDate").value,cycle=id==="custom"?parseCycle($("#customCycleText").value):copy(C.presets()[id]&&C.presets()[id].cycle);if(!anchor){toast("حدد أول يوم في دورة الدوام");return}if(!cycle||!cycle.length){toast("اكتب نمطًا صحيحًا مثل: نهاري، ليلي، راحة");return}data.profile.name=$("#settingsName").value.trim();data.settings.timezone=$("#timezoneSelect").value||"Asia/Muscat";data.settings.reminderBefore=Number($("#reminderBefore").value)||60;data.settings.dayStart=$("#workStart").value||"07:00";data.settings.dayEnd=$("#workEnd").value||"19:00";data.settings.nightStart=$("#nightStart").value||"19:00";data.settings.nightEnd=$("#nightEnd").value||"07:00";data.settings.customCycleText=$("#customCycleText").value.trim();S.anchor=anchor;S.patternId=id;S.patternName=patternName(id);S.cycle=applyTimes(cycle);save("تم حفظ جدول دوامك");renderAll();showPage("calendar")}
function showPage(id,opts){if(!$("#"+id))id="calendar";page=id;document.body.classList.add("panel-open");$$(".page").forEach(function(x){x.classList.toggle("active",x.id===id||((id==="home"||id==="settings")&&x.id==="calendar"))});$$("[data-page]").forEach(function(x){x.classList.toggle("active",x.dataset.page===id)});window.scrollTo({top:0,behavior:"auto"});if(!(opts&&opts.fromHistory)){var next=location.pathname+location.search+"#"+id;if(opts&&opts.replace)history.replaceState({dawamiPage:id},"",next);else if(!(history.state&&history.state.dawamiPage===id&&!history.state.dawamiModal))history.pushState({dawamiPage:id},"",next)}if(id==="calendar")renderCalendar();if(id==="settings")renderSettings()}
function buildSetup(){setupStep=1;var ids=["14-14","28-14","7-7","4-4","2d2n4","5-2","custom"],box=$("#setupPatterns");box.innerHTML=ids.map(function(id){return'<button class="pattern" type="button" data-setup-pattern="'+id+'">'+patternName(id)+"</button>"}).join("");setupPattern=C.presets()[S.patternId]?S.patternId:(S.patternId==="custom"?"custom":"14-14");$$("[data-setup-pattern]",box).forEach(function(b){b.onclick=function(){setupPattern=b.dataset.setupPattern;$$("[data-setup-pattern]",box).forEach(function(x){x.classList.toggle("active",x===b)});$("#setupCustomWrap").hidden=setupPattern!=="custom";renderSetupPreview()}});var active=$('[data-setup-pattern="'+setupPattern+'"]',box);if(active)active.classList.add("active");$("#setupName").value=data.profile.name||"";$("#setupTimezone").value=data.settings.timezone||"Asia/Muscat";$("#setupAnchor").value=S.anchor||today;$("#setupStart").value=data.settings.dayStart;$("#setupEnd").value=data.settings.dayEnd;$("#setupNightStart").value=data.settings.nightStart;$("#setupNightEnd").value=data.settings.nightEnd;$("#setupAnnualBalance").value=data.settings.annualBalance;$("#setupCarryOver").value=data.settings.carryOver;$("#setupCustomCycle").value=data.settings.customCycleText||"";$("#setupCustomWrap").hidden=setupPattern!=="custom";showSetupStep(1);renderSetupPreview()}
function renderSetupPreview(){var cyc=setupPattern==="custom"?parseCycle($("#setupCustomCycle").value):copy(C.presets()[setupPattern]&&C.presets()[setupPattern].cycle),box=$("#setupPreview");box.innerHTML="";if(!cyc||!cyc.length){box.innerHTML='<div class="empty-state">اكتب دورة صحيحة للمعاينة.</div>';return}for(var i=0;i<60;i++){var e=C.normalizeEvent(cyc[i%cyc.length]),x=document.createElement("i");x.className=classFor(e);x.title=(i+1)+" • "+textFor(e);box.appendChild(x)}}
function showSetupStep(step){setupStep=Math.min(7,Math.max(1,step));$$("[data-setup-step]").forEach(function(x){x.hidden=Number(x.dataset.setupStep)!==setupStep});$("#setupStepLabel").textContent=setupStep+" من 7";$("#setupProgress").style.width=(setupStep/7*100)+"%";$("#setupPrev").hidden=setupStep===1;$("#setupNext").hidden=setupStep===7;$("#finishSetup").hidden=setupStep!==7;if(setupStep===7)renderSetupPreview()}
function validateSetupStep(){if(setupStep===3&&setupPattern==="custom"&&!parseCycle($("#setupCustomCycle").value)){toast("اكتب دورة صحيحة مثل: نهاري، ليلي، راحة");return false}if(setupStep===4&&!$("#setupAnchor").value){toast("حدد أول يوم في الدورة");return false}return true}
function finishSetup(){var anchor=$("#setupAnchor").value,cycle=setupPattern==="custom"?parseCycle($("#setupCustomCycle").value):copy(C.presets()[setupPattern]&&C.presets()[setupPattern].cycle);if(!anchor||!cycle||!cycle.length){toast("راجع بيانات الجدول");return}data.profile.name=$("#setupName").value.trim();data.settings.timezone=$("#setupTimezone").value||"Asia/Muscat";data.settings.dayStart=$("#setupStart").value||"07:00";data.settings.dayEnd=$("#setupEnd").value||"19:00";data.settings.nightStart=$("#setupNightStart").value||"19:00";data.settings.nightEnd=$("#setupNightEnd").value||"07:00";data.settings.annualBalance=Math.max(0,Number($("#setupAnnualBalance").value)||0);data.settings.carryOver=Math.max(0,Number($("#setupCarryOver").value)||0);data.settings.customCycleText=$("#setupCustomCycle").value.trim();S.anchor=anchor;S.patternId=setupPattern;S.patternName=patternName(setupPattern);S.cycle=applyTimes(cycle);data.onboarded=true;save();close("setupModal");renderAll();toast("تمام، جدولك جاهز لـ60 يوم وقدام")}
async function toggleNotify(){if(data.settings.notificationEnabled){data.settings.notificationEnabled=false;clearNotifyTimers();save();renderSettings();toast("تم إيقاف التنبيهات");return}if(!("Notification"in window)||!("serviceWorker"in navigator)){toast("التنبيهات غير مدعومة في هذا المتصفح");return}var result=Notification.permission;if(result==="default")result=await Notification.requestPermission();if(result!=="granted"){toast("ما تم السماح بالتنبيهات");return}data.settings.notificationEnabled=true;save();renderSettings();scheduleNotify();toast("تم التفعيل أثناء تشغيل التطبيق")}
function scheduleNotify(){clearNotifyTimers();if(!data.settings.notificationEnabled||!("Notification"in window)||Notification.permission!=="granted")return;var before=Number(data.settings.reminderBefore)||60,next=C.nextShift(S,Date.now(),tz),opt=data.settings.notifyOptions||{};if(next){queueNotice(next.start-before*60000,"دوامك بعد "+reminderLabel(before),textFor(next.event)+" يبدأ "+fmtTime(next.start),"dawami-shift");if(opt.return24)queueNotice(next.start-86400000,"باقي 24 ساعة على الرجوع",textFor(next.event)+" يبدأ "+fmtTime(next.start),"dawami-return");if(opt.nightShift&&next.event.type==="night")queueNotice(next.start,"بدأ دوامك الليلي",fmtTime(next.start),"dawami-night");if(opt.nightBefore){var night=C.zonedEpoch(add(next.date,-1),"21:00",tz);queueNotice(night,"بكرة بداية دوامك",textFor(next.event)+" الساعة "+next.event.start,"dawami-night-before")}}}
async function forceSiteUpdate(){try{toast("جاري تحديث الموقع…");if("serviceWorker"in navigator){var regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(function(r){return r.unregister()}))}if("caches"in window){var keys=await caches.keys();await Promise.all(keys.map(function(k){return caches.delete(k)}))}setTimeout(function(){location.replace(location.pathname+"?fresh=10.0#"+page)},350)}catch(e){location.reload()}}
function download(){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="dawami-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(function(){URL.revokeObjectURL(url)},500)}

function parseCycle(text){var items=String(text||"").split(/[،,\n]+/).map(function(x){return x.trim()}).filter(Boolean);if(!items.length)return null;var out=[];for(var i=0;i<items.length;i++){var t=items[i],e;if(/ليل/.test(t))e={type:"night",label:"دوام ليلي",start:data.settings.nightStart||"19:00",end:data.settings.nightEnd||"07:00"};else if(/نهار|دوام|عمل/.test(t))e={type:"day",label:"دوام",start:data.settings.dayStart||"07:00",end:data.settings.dayEnd||"19:00"};else if(/راح|إجاز|اجاز|أوف|اوف/.test(t))e={type:"off",label:"راحة"};else if(/تدريب/.test(t))e={type:"training",label:"تدريب",start:data.settings.dayStart||"07:00",end:data.settings.dayEnd||"19:00"};else return null;out.push(e)}return out}
function snapshot(label){undoStack.push({label:label||"تعديل",overrides:copy(S.overrides),leaves:copy(S.leaves)});if(undoStack.length>15)undoStack.shift()}
function undoLastChange(){var last=undoStack.pop();if(!last){toast("ما فيه تعديل للتراجع");return}S.overrides=last.overrides;S.leaves=last.leaves;save();renderAll();toast("تم التراجع عن "+last.label)}
function bindCalendarDay(button,k){var hold=null,longPress=false,moved=false;button.addEventListener("pointerdown",function(){moved=false;longPress=false;hold=setTimeout(function(){if(data.settings.scheduleLocked){toast("افتح قفل الجدول أولًا");return}longPress=true;selectedDates.add(k);pulse(18);renderCalendar()},480)});button.addEventListener("pointermove",function(){moved=true;clearTimeout(hold)});button.addEventListener("pointerup",function(){clearTimeout(hold)});button.addEventListener("pointercancel",function(){clearTimeout(hold)});button.onclick=function(e){if(longPress||moved){e.preventDefault();return}if(selectedDates.size){toggleSelectedDate(k)}else showDay(k)}}
function toggleSelectedDate(k){if(selectedDates.has(k))selectedDates.delete(k);else selectedDates.add(k);pulse(7);renderCalendar()}
function updateSelectionBar(){var bar=$("#selectionBar");bar.hidden=!selectedDates.size;$("#selectionCount").textContent=selectedDates.size;$("#pasteSelected").disabled=!dayClipboard}
function clearSelection(){selectedDates.clear();renderCalendar()}
function copySelectedDays(){if(!selectedDates.size){toast("حدد يومًا أولًا");return}var k=Array.from(selectedDates).sort()[0];dayClipboard=copy(C.eventsForDate(S,k));updateSelectionBar();toast("تم نسخ "+textFor(dayClipboard[0]))}
function pasteSelectedDays(){if(data.settings.scheduleLocked){toast("الجدول مقفول");return}if(!dayClipboard||!selectedDates.size){toast("انسخ يومًا وحدد الأيام المطلوبة");return}snapshot("اللصق");selectedDates.forEach(function(k){S.overrides[k]=copy(dayClipboard)});save();renderAll();toast("تم اللصق على "+selectedDates.size+" يوم")}
function quickExtraSelected(){if(data.settings.scheduleLocked){toast("الجدول مقفول");return}if(!selectedDates.size)return;snapshot("إضافة الإكسترا");selectedDates.forEach(function(k){var base=S.overrides[k]!==undefined?(Array.isArray(S.overrides[k])?copy(S.overrides[k]):[copy(S.overrides[k])]):copy(C.baseEvents(S,k));base.push({type:"overtime",label:"إكسترا دي",start:data.settings.dayStart,end:data.settings.dayEnd});S.overrides[k]=base});save();renderAll();toast("تمت إضافة الإكسترا")}
function setCalendarView(view){calendarView=view;data.settings.calendarView=view;save();renderCalendar()}
function jumpToDate(k){selectedDay=k;month=k.slice(0,7)+"-01";calendarView="month";data.settings.calendarView="month";save();close("calendarToolsModal");renderCalendar();setTimeout(function(){var b=$('[data-date="'+k+'"]');if(b){b.classList.add("selected");b.scrollIntoView({block:"center",behavior:"smooth"})}},100)}
function findRest(){for(var i=0;i<740;i++){var k=add(today,i);if(C.isRest(C.primaryEvent(S,k))){$("#firstRestResult").textContent=fmtKey(k,{weekday:"long",day:"numeric",month:"long"});jumpToDate(k);toast("هذا أول يوم راحة");return}}toast("ما حصلنا يوم راحة قريب")}
function annualUsedValue(year){return C.annualLeaveUsed(S,year,!!data.settings.deductRest)}
function annualRemainingValue(year){return Math.max(0,(Number(data.settings.annualBalance)||0)+(Number(data.settings.carryOver)||0)-annualUsedValue(year))}
function nextRecordedLeave(){return(S.leaves||[]).filter(function(l){return l.end>=today}).sort(function(a,b){return a.start.localeCompare(b.start)})[0]||null}
function leaveTypeText(t){return{annual:"سنوية",sick:"مرضية",emergency:"طارئة",comp:"تعويضية",unpaid:"بدون راتب",training:"تدريب"}[t]||"إجازة"}
function renderLeaves(){var year=Number(today.slice(0,4)),used=annualUsedValue(year),remaining=annualRemainingValue(year),next=nextRecordedLeave();$("#annualUsed").textContent=used+" يوم";$("#annualRemaining").textContent=remaining+" يوم";$("#nextLeaveSetting").textContent=next?fmtKey(next.start):"لا توجد";$("#leaveBalanceBig").textContent=remaining+" يوم";$("#leaveUsedBig").textContent=used+" يوم";$("#leaveCarryBig").textContent=(Number(data.settings.carryOver)||0)+" يوم";var box=$("#leaveList"),list=(S.leaves||[]).slice().sort(function(a,b){return b.start.localeCompare(a.start)});if(!list.length){box.innerHTML='<div class="empty-state"><b>ما سجلت إجازات بعد</b>أضف أول إجازة من النموذج فوق.</div>';return}box.innerHTML=list.map(function(l){return'<div class="leave-item"><div><b>'+esc(l.name||leaveTypeText(l.type))+'</b><small>'+fmtKey(l.start,{day:"numeric",month:"short"})+' — '+fmtKey(l.end,{day:"numeric",month:"short"})+(l.half?" • نصف يوم":"")+'</small></div><button type="button" data-delete-leave="'+esc(l.id)+'" aria-label="حذف">×</button></div>'}).join("");$("[data-delete-leave]",box).forEach(function(b){b.onclick=function(){if(!confirm("تحذف هذه الإجازة؟"))return;snapshot("حذف الإجازة");S.leaves=S.leaves.filter(function(l){return l.id!==b.dataset.deleteLeave});save();renderAll();toast("تم حذف الإجازة")}})}
function saveLeaveRecord(){var start=$("#leaveStart").value,end=$("#leaveEnd").value||start,type=$("#leaveType").value,half=$("#leaveHalf").checked;if(!start||!end||end<start){toast("تأكد من تاريخ البداية والنهاية");return}if(half&&start!==end){toast("نصف اليوم يكون في تاريخ واحد");return}snapshot("إضافة الإجازة");S.leaves.push({id:"leave-"+Date.now(),start:start,end:end,type:type,half:half,name:$("#leaveName").value.trim(),reason:$("#leaveReason").value.trim(),createdAt:new Date().toISOString()});save();$("#leaveName").value="";$("#leaveReason").value="";$("#leaveHalf").checked=false;renderAll();toast("تمت إضافة الإجازة")}
function payEstimateFor(y,m){var st=C.monthStats(S,y,m),p=data.settings.pay||{},rate=(Number(p.basic)||0)/(Number(p.basicHours)||160),extra=st.overtimeHours*rate*(Number(p.overtimeMultiplier)||1.5),allow=st.night*(Number(p.nightAllowance)||0)+st.workDays*(Number(p.siteAllowance)||0);return{total:(Number(p.basic)||0)+extra+allow,stats:st,extra:extra,allow:allow}}
function savePay(){var p=data.settings.pay;p.enabled=$("#payEnabled").checked;p.basic=Number($("#payBasic").value)||0;p.basicHours=Number($("#payBasicHours").value)||160;p.overtimeMultiplier=Number($("#payOvertimeMultiplier").value)||1.5;p.nightAllowance=Number($("#payNightAllowance").value)||0;p.siteAllowance=Number($("#paySiteAllowance").value)||0;p.payDay=Math.min(31,Math.max(1,Number($("#payDay").value)||25));save();renderAdvanced();renderSettings()}
function renderPay(){var p=data.settings.pay||{},tp=parts(today),cur=payEstimateFor(tp.year,tp.month),pd=new Date(Date.UTC(tp.year,tp.month-2,1)),prev=payEstimateFor(pd.getUTCFullYear(),pd.getUTCMonth()+1),diff=cur.total-prev.total;$("#payEstimate").textContent=p.enabled?cur.total.toFixed(3)+" ر.ع":"غير مفعل";$("#payCompare").textContent=p.enabled?(diff===0?"نفس الشهر السابق":(diff>0?"+":"")+diff.toFixed(3)+" ر.ع عن الشهر السابق"):"فعّله إذا تبي حسابًا تقديريًا"}
function collectInsights(){var tp=parts(today),cur=C.monthStats(S,tp.year,tp.month),pd=new Date(Date.UTC(tp.year,tp.month-2,1)),prev=C.monthStats(S,pd.getUTCFullYear(),pd.getUTCMonth()+1),nextMonthDate=new Date(Date.UTC(tp.year,tp.month,1)),ny=nextMonthDate.getUTCFullYear(),nm=nextMonthDate.getUTCMonth()+1,nfirst=ny+"-"+String(nm).padStart(2,"0")+"-01",rest=C.longestStreak(S,nfirst,C.daysInMonth(ny,nm),function(ev){return!ev.some(C.isWork)}),work=C.longestStreak(S,today.slice(0,7)+"-01",C.daysInMonth(tp.year,tp.month),function(ev){return ev.some(C.isWork)}),night=C.longestStreak(S,today,60,function(ev){return ev.some(function(x){return x.type==="night"})}),state=C.nowStatus(S,Date.now(),tz),nextBlock=C.restBlock(S,today,false),left=nextBlock?C.workDaysBetween(S,today,nextBlock.start):0,payDay=Math.min(C.daysInMonth(tp.year,tp.month),Number((data.settings.pay||{}).payDay)||25),payKey=tp.year+"-"+String(tp.month).padStart(2,"0")+"-"+String(payDay).padStart(2,"0"),payEvent=C.primaryEvent(S,payKey),firstRest=null;for(var i=0;i<90&&!firstRest;i++){var k=add(today,i);if(C.isRest(C.primaryEvent(S,k)))firstRest=k}
 return[{icon:"↗",text:"أمامك "+left+" أيام دوام فعلية قبل الراحة",sub:nextBlock?"تبدأ "+fmtKey(nextBlock.start):"اضبط جدولك أولًا"},{icon:"◌",text:"عندك "+rest.length+" أيام راحة متصلة الشهر القادم",sub:rest.length?fmtKey(rest.start)+" إلى "+fmtKey(rest.end):"لا توجد فترة متصلة"},{icon:"◷",text:cur.hours===prev.hours?"ساعاتك مثل الشهر الماضي":("هذا الشهر "+Math.abs(Math.round(cur.hours-prev.hours))+" ساعة "+(cur.hours>prev.hours?"أكثر":"أقل")+" من الماضي"),sub:Math.round(cur.hours)+" ساعة هذا الشهر"},{icon:"▥",text:"أطول فترة دوام متواصلة هذا الشهر "+work.length+" أيام",sub:fmtKey(work.start)+" إلى "+fmtKey(work.end)},{icon:"☾",text:night.length?"عندك "+night.length+" دوام ليلي متتالٍ":"ما عندك دوام ليلي متتالٍ قريب",sub:night.length?fmtKey(night.start):"خلال 60 يومًا"},{icon:"✓",text:firstRest?"أفضل يوم لموعد شخصي: "+fmtKey(firstRest,{weekday:"long",day:"numeric",month:"long"}):"ما لقينا يوم راحة قريب",sub:"أول يوم راحة متاح"},{icon:"◉",text:"يوم راتبك يوافق "+(C.isWork(payEvent)?"دوام":"راحة"),sub:fmtKey(payKey,{weekday:"long",day:"numeric",month:"long"})},{icon:"⌁",text:state.nextShift?"دوامك القادم "+textFor(state.nextShift.event):"ما فيه دوام قادم",sub:state.nextShift?fmtTime(state.nextShift.start):"—"}]}
function renderInsights(){var insights=collectInsights(),home=$("#insightsGrid"),full=$("#insightList");home.innerHTML=insights.slice(0,4).map(function(x){return'<div class="insight-chip"><i>'+x.icon+'</i><b>'+esc(x.text)+'</b><small>'+esc(x.sub)+'</small></div>'}).join("");full.innerHTML=insights.map(function(x){return'<div class="insight-line"><i>'+x.icon+'</i><div><b>'+esc(x.text)+'</b><small>'+esc(x.sub)+'</small></div></div>'}).join("");var ops=C.bestLeave(S,today,240,3);$("#bestLeaveList").innerHTML=ops.length?ops.slice(0,3).map(function(o){return'<div class="opportunity">إذا أخذت <b>'+o.leaveDays+' '+(o.leaveDays===1?"يوم":"أيام")+'</b> من '+fmtKey(o.start)+' إلى '+fmtKey(o.end)+'، تحصل على <b>'+o.totalBreak+' أيام راحة متصلة</b>.</div>'}).join(""):'<div class="empty-state">ما حصلنا فرصة مناسبة في الفترة القادمة.</div>'}
function renderAdvanced(){renderLeaves();renderPay();renderInsights();$("#toggleScheduleLock").classList.toggle("active",!!data.settings.scheduleLocked);$("#lockHint").textContent=data.settings.scheduleLocked?"الجدول مقفول الآن":"امنع التعديل بالخطأ";$("#installApp").textContent=window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches?"دوامي مثبت":"تثبيت دوامي"}
function planTrip(){var wanted=Number($("#tripDays").value)||7,ops=C.bestLeave(S,today,365,7),choice=ops.filter(function(o){return o.totalBreak>=wanted}).sort(function(a,b){return a.leaveDays-b.leaveDays||a.start.localeCompare(b.start)})[0]||ops[0];$("#tripResult").textContent=choice?"خذ "+choice.leaveDays+" أيام إجازة من "+fmtKey(choice.start)+" إلى "+fmtKey(choice.end)+" لتحصل على "+choice.totalBreak+" أيام راحة متصلة.":"ما حصلنا نافذة مناسبة، جرّب عدد أيام مختلف."}
function compareDataFile(file){var reader=new FileReader();reader.onload=function(){try{var raw=JSON.parse(reader.result),other=raw.schedule||raw;if(!other.cycle||!other.anchor)throw new Error("bad");var common=[];for(var i=0;i<120;i++){var k=add(today,i);if(C.isRest(C.primaryEvent(S,k))&&C.isRest(C.primaryEvent(other,k)))common.push(k)}compareSchedule=other;$("#compareResult").textContent=common.length?"عندكم "+common.length+" يوم راحة مشترك خلال 120 يومًا. أولها "+fmtKey(common[0],{weekday:"long",day:"numeric",month:"long"})+".":"ما لقينا أيام راحة مشتركة خلال 120 يومًا."}catch(e){$("#compareResult").textContent="الملف غير صالح أو لا يحتوي على جدول دوامي."}};reader.readAsText(file)}
function prepareShare(){var a=today,b=add(today,30);$("#exportStart").value=a;$("#exportEnd").value=b}
function validExportRange(){var a=$("#exportStart").value,b=$("#exportEnd").value;if(!a||!b||b<a||C.diffDays(a,b)>366){toast("اختر فترة صحيحة لا تتجاوز سنة");return null}return{start:a,end:b}}
function downloadBlob(content,type,name){var blob=content instanceof Blob?content:new Blob([content],{type:type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url)},800)}
function icsStamp(k,time){return k.replace(/-/g,"")+"T"+String(time||"00:00").replace(":","")+"00"}
function exportICS(){var r=validExportRange();if(!r)return;var rows=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Dawami//AR","CALSCALE:GREGORIAN","METHOD:PUBLISH","X-WR-CALNAME:دوامي"];C.range(r.start,r.end).forEach(function(k){C.eventsForDate(S,k).forEach(function(e,i){if(!C.isWork(e)&&["annual","sick","emergency","comp","unpaid","training"].indexOf(e.type)<0)return;rows.push("BEGIN:VEVENT","UID:"+k+"-"+i+"@dawami","SUMMARY:"+textFor(e).replace(/[,;]/g," "));if(C.isWork(e)){var endKey=e.end<=e.start?add(k,1):k;rows.push("DTSTART;TZID="+tz+":"+icsStamp(k,e.start),"DTEND;TZID="+tz+":"+icsStamp(endKey,e.end))}else rows.push("DTSTART;VALUE=DATE:"+k.replace(/-/g,""),"DTEND;VALUE=DATE:"+add(k,1).replace(/-/g,""));if(e.note)rows.push("DESCRIPTION:"+String(e.note).replace(/[\n,;]/g," "));if(e.location||e.job)rows.push("LOCATION:"+String(e.location||e.job).replace(/[,;]/g," "));rows.push("END:VEVENT")})});rows.push("END:VCALENDAR");downloadBlob(rows.join("\r\n"),"text/calendar;charset=utf-8","dawami-"+r.start+"-"+r.end+".ics");toast("تم تجهيز ملف التقويم")}
function exportCSV(){var r=validExportRange();if(!r)return;var rows=[["التاريخ","اليوم","النوع","البداية","النهاية","الساعات","الموقع","الجوب","الملاحظة"]];C.range(r.start,r.end).forEach(function(k){C.eventsForDate(S,k).forEach(function(e){rows.push([k,fmtKey(k,{weekday:"long"}),textFor(e),e.start||"",e.end||"",C.isWork(e)?C.eventHours(e,0):0,e.location||"",e.job||"",e.note||""])})});var csv="\ufeff"+rows.map(function(row){return row.map(function(v){return'"'+String(v).replace(/"/g,'""')+'"'}).join(",")}).join("\n");downloadBlob(csv,"text/csv;charset=utf-8","dawami-report-"+r.start+".csv");toast("تم تجهيز التقرير")}
async function shareTextSummary(){var r=validExportRange();if(!r)return;var state=C.nowStatus(S,Date.now(),tz),block=C.restBlock(S,today,false),text="ملخص دوامي\n"+(state.label||"")+"\n"+(block?"الراحة القادمة: "+fmtKey(block.start,{weekday:"long",day:"numeric",month:"long"})+" لمدة "+block.length+" أيام\n":"")+"الدوام القادم: "+(state.nextShift?fmtTime(state.nextShift.start):"—");try{if(navigator.share)await navigator.share({title:"دوامي",text:text});else{await navigator.clipboard.writeText(text);toast("تم نسخ الملخص")}}catch(e){}}
function shareScheduleImage(){var r=validExportRange();if(!r)return;var canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),days=C.range(r.start,r.end).slice(0,7);canvas.width=1080;canvas.height=1350;ctx.fillStyle=data.settings.theme==="dark"?"#08111d":"#f3f6fa";ctx.fillRect(0,0,1080,1350);ctx.direction="rtl";ctx.textAlign="right";ctx.fillStyle=data.settings.theme==="dark"?"#ffffff":"#101828";ctx.font="bold 74px -apple-system,Arial";ctx.fillText("جدول دوامي",960,120);ctx.font="34px -apple-system,Arial";ctx.fillStyle=data.settings.colors.accent;ctx.fillText(fmtKey(days[0],{day:"numeric",month:"long"})+" — "+fmtKey(days[days.length-1],{day:"numeric",month:"long"}),960,180);days.forEach(function(k,i){var y=245+i*145,e=C.primaryEvent(S,k),color=classFor(e)==="work"?data.settings.colors.work:classFor(e)==="off"?data.settings.colors.off:classFor(e)==="extra"?data.settings.colors.extra:data.settings.colors.annual;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(80,y,920,115,28);ctx.fill();ctx.fillStyle=classFor(e)==="work"?"#16120a":"#fff";ctx.font="bold 42px -apple-system,Arial";ctx.fillText(fmtKey(k,{weekday:"long",day:"numeric",month:"short"}),930,y+48);ctx.font="bold 32px -apple-system,Arial";ctx.fillText(C.eventsForDate(S,k).map(textFor).join(" + "),930,y+90)});ctx.fillStyle=data.settings.theme==="dark"?"#91A0B5":"#667085";ctx.font="28px -apple-system,Arial";ctx.fillText("دوامي • وقتك قدامك بوضوح",960,1310);canvas.toBlob(async function(blob){if(!blob)return;var file=new File([blob],"dawami-week.png",{type:"image/png"});try{if(navigator.canShare&&navigator.canShare({files:[file]}))await navigator.share({files:[file],title:"جدول دوامي"});else downloadBlob(blob,"image/png","dawami-week.png")}catch(e){}}, "image/png")}
function saveGeneralSettings(){data.settings.annualBalance=Math.max(0,Number($("#annualBalance").value)||0);data.settings.carryOver=Math.max(0,Number($("#carryOver").value)||0);data.settings.deductRest=$("#deductRest").checked;data.settings.notifyOptions={nightBefore:$("#notifyNightBefore").checked,return24:$("#notifyReturn24").checked,nightShift:$("#notifyNightShift").checked};save();renderAdvanced();scheduleNotify()}
function clearNotifyTimers(){notifyTimers.forEach(clearTimeout);notifyTimers=[]}
function queueNotice(at,title,body,tag){var delay=at-Date.now();if(delay<=0||delay>=2147483647)return;notifyTimers.push(setTimeout(async function(){try{var reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body:body,icon:"icon.svg",tag:tag})}catch(e){}scheduleNotify()},delay))}

function pulse(ms){try{if(navigator.vibrate)navigator.vibrate(ms||7)}catch(e){}}
function installTouchUX(){
 document.addEventListener("pointerdown",function(e){var target=e.target&&e.target.closest?e.target.closest("button,.day"):null;if(!target||target.disabled)return;target.classList.add("is-pressing");var r=target.getBoundingClientRect(),wave=document.createElement("span");wave.className="tap-wave";wave.style.left=(e.clientX-r.left)+"px";wave.style.top=(e.clientY-r.top)+"px";target.appendChild(wave);setTimeout(function(){wave.remove()},520);if(target.matches(".day,[data-day-type],.primary,.today-button"))pulse(6)},{passive:true});
 ["pointerup","pointercancel","pointerleave"].forEach(function(type){document.addEventListener(type,function(e){var target=e.target&&e.target.closest?e.target.closest("button,.day"):null;if(target)target.classList.remove("is-pressing")},true)})
}
function bindDaySheet(){$$(".modal .sheet").forEach(function(sheet){var modal=sheet.closest(".modal"),head=$(".sheet-head",sheet),grab=$(".sheet-grabber",sheet),start=0,drag=0,active=false;if(!head||!grab)return;function begin(e){if(sheet.scrollTop>0)return;active=true;start=e.changedTouches[0].clientY;drag=0;sheet.classList.add("dragging");sheet.classList.remove("settling")}function move(e){if(!active)return;drag=Math.max(0,e.changedTouches[0].clientY-start);sheet.style.transform="translate3d(0,"+Math.min(drag,280)+"px,0)";if(drag>4)e.preventDefault()}function end(){if(!active)return;active=false;sheet.classList.remove("dragging");sheet.classList.add("settling");if(drag>105){sheet.style.transform="translate3d(0,110%,0)";pulse(10);setTimeout(function(){close(modal.id);sheet.style.transform="";sheet.classList.remove("settling")},190)}else{sheet.style.transform="";setTimeout(function(){sheet.classList.remove("settling")},320)}}[head,grab].forEach(function(handle){handle.addEventListener("touchstart",begin,{passive:true});handle.addEventListener("touchmove",move,{passive:false});handle.addEventListener("touchend",end,{passive:true});handle.addEventListener("touchcancel",end,{passive:true})})})}

function bind(){installTouchUX();bindDaySheet();
 $$("[data-page]").forEach(function(b){b.onclick=function(){showPage(b.dataset.page)}});$$("[data-open-page]").forEach(function(b){b.onclick=function(){showPage(b.dataset.openPage)}});$$("[data-close]").forEach(function(b){b.onclick=function(){close(b.dataset.close)}});
 $("#themeBtn").onclick=function(){data.settings.theme=data.settings.theme==="dark"?"light":"dark";save();renderAll()};$("#darkSwitch").onclick=$("#themeBtn").onclick;
 $("#nextMonth").onclick=function(){moveMonth(1)};$("#prevMonth").onclick=function(){moveMonth(-1)};$("#monthLabel").onclick=function(){month=today.slice(0,7)+"-01";selectedDay=today;renderCalendar()};
 $$("[data-calendar-view]").forEach(function(b){b.onclick=function(){setCalendarView(b.dataset.calendarView)}});$("#calendarTools").onclick=function(){open("calendarToolsModal")};$("#clearSelection").onclick=clearSelection;$("#copySelected").onclick=copySelectedDays;$("#pasteSelected").onclick=pasteSelectedDays;$("#quickExtraSelected").onclick=quickExtraSelected;$("#undoSelected").onclick=undoLastChange;
 $("#toggleScheduleLock").onclick=function(){data.settings.scheduleLocked=!data.settings.scheduleLocked;save();renderAdvanced();close("calendarToolsModal");toast(data.settings.scheduleLocked?"تم قفل الجدول":"تم فتح الجدول")};$("#startMultiSelect").onclick=function(){if(data.settings.scheduleLocked){toast("افتح قفل الجدول أولًا");return}close("calendarToolsModal");toast("اضغط الأيام التي تريد تحديدها")};$("#findFirstRest").onclick=findRest;$("#undoLast").onclick=function(){close("calendarToolsModal");undoLastChange()};
 $("#toolsOpenLeaves").onclick=function(){close("calendarToolsModal");renderLeaves();open("leavesModal")};$("#toolsOpenShare").onclick=function(){close("calendarToolsModal");prepareShare();open("shareModal")};$("#openLeaves").onclick=function(){renderLeaves();open("leavesModal")};$("#openShare").onclick=function(){prepareShare();open("shareModal")};$("#openInsights").onclick=function(){renderInsights();open("insightsModal")};
 document.querySelectorAll("[data-palette]").forEach(function(b){b.onclick=function(){data.settings.colorTheme=b.dataset.palette;data.settings.colors=copy(PALETTES[b.dataset.palette]||DEFAULT_COLORS);save();renderAll();toast("تم تطبيق مجموعة الألوان")}});document.querySelectorAll("[data-color-key]").forEach(function(input){input.oninput=function(){data.settings.colorTheme="custom";data.settings.colors=data.settings.colors||copy(DEFAULT_COLORS);data.settings.colors[input.dataset.colorKey]=input.value;applyPalette();document.querySelectorAll("[data-palette]").forEach(function(b){b.classList.remove("active");b.setAttribute("aria-pressed","false")});save()};input.onchange=function(){renderAll();toast("تم حفظ اللون")}});$("#resetColors").onclick=function(){data.settings.colorTheme="gold";data.settings.colors=copy(DEFAULT_COLORS);save();renderAll();toast("رجعنا الألوان الأصلية")};
 $("#patternSelect").onchange=function(){var id=this.value,cyc=id==="custom"?parseCycle($("#customCycleText").value):(C.presets()[id]&&copy(C.presets()[id].cycle));$("#customCycleSettings").hidden=id!=="custom";$("#nightTimes").hidden=id!=="2d2n4"&&!(cyc||[]).some(function(e){return C.normalizeEvent(e).type==="night"});$("#cyclePreview").innerHTML=(cyc||[]).map(function(e){return'<i class="'+classFor(C.normalizeEvent(e))+'"></i>'}).join("")};$("#customCycleText").oninput=function(){if($("#patternSelect").value==="custom"){var c=parseCycle(this.value);$("#cyclePreview").innerHTML=(c||[]).map(function(e){return'<i class="'+classFor(e)+'"></i>'}).join("")}};$("#saveSettings").onclick=savePattern;
 $("#notifySwitch").onclick=toggleNotify;$("#reminderBefore").onchange=function(){data.settings.reminderBefore=Number(this.value)||60;save();renderSettings();scheduleNotify();toast("تم تغيير وقت التنبيه")};["notifyNightBefore","notifyReturn24","notifyNightShift","annualBalance","carryOver","deductRest"].forEach(function(id){$("#"+id).onchange=saveGeneralSettings});$("#forceUpdate").onclick=forceSiteUpdate;
 $("#payEnabled").onchange=savePay;["payBasic","payBasicHours","payOvertimeMultiplier","payNightAllowance","paySiteAllowance","payDay"].forEach(function(id){$("#"+id).onchange=savePay});
 $("#toggleEditDay").onclick=function(){if(data.settings.scheduleLocked){toast("الجدول مقفول");return}var edit=$("#editDay"),sheet=$("#dayModal .sheet");edit.hidden=!edit.hidden;if(!edit.hidden){edit.classList.remove("reveal");void edit.offsetWidth;edit.classList.add("reveal");setTimeout(function(){sheet.scrollTo({top:Math.max(0,edit.offsetTop-18),behavior:"smooth"})},60)}else edit.classList.remove("reveal");pulse(8)};$$("[data-day-type]").forEach(function(b){b.onclick=function(){selectDayType(b.dataset.dayType)}});$("#dayType").onchange=function(){selectDayType(this.value)};
 $("#saveDay").onclick=function(){if(data.settings.scheduleLocked){toast("الجدول مقفول");return}var type=$("#dayType").value,timed=type==="overtime"||type==="training",event={type:type,label:textFor({type:type}),start:timed?($("#dayStart").value||data.settings.dayStart):"",end:timed?($("#dayEnd").value||data.settings.dayEnd):"",location:$("#dayLocation").value.trim(),job:$("#dayJob").value.trim(),note:$("#dayNote").value.trim()};snapshot("تعديل اليوم");if($("#dayAppend").checked){var base=S.overrides[selectedDay]!==undefined?(Array.isArray(S.overrides[selectedDay])?copy(S.overrides[selectedDay]):[copy(S.overrides[selectedDay])]):copy(C.baseEvents(S,selectedDay));base.push(event);S.overrides[selectedDay]=base}else S.overrides[selectedDay]=event;save();close("dayModal");renderAll();toast("تم حفظ اليوم وتلوينه")};$("#resetDay").onclick=function(){if(data.settings.scheduleLocked){toast("الجدول مقفول");return}snapshot("إرجاع اليوم");delete S.overrides[selectedDay];save();close("dayModal");renderAll();toast("رجع اليوم لجدولك")};
 $("#saveLeave").onclick=saveLeaveRecord;$("#leaveStart").onchange=function(){if(!$("#leaveEnd").value||$("#leaveEnd").value<=$("#leaveStart").value)$("#leaveEnd").value=$("#leaveStart").value};$("#planTrip").onclick=planTrip;$("#compareFile").onchange=function(){if(this.files[0])compareDataFile(this.files[0])};
 $("#exportICS").onclick=exportICS;$("#exportCSV").onclick=exportCSV;$("#shareText").onclick=shareTextSummary;$("#shareImage").onclick=shareScheduleImage;$("#printReport").onclick=function(){close("shareModal");setTimeout(function(){window.print()},250)};
 $("#showSetup").onclick=function(){buildSetup();open("setupModal")};$("#setupPrev").onclick=function(){showSetupStep(setupStep-1)};$("#setupNext").onclick=function(){if(validateSetupStep())showSetupStep(setupStep+1)};$("#finishSetup").onclick=finishSetup;$("#setupCustomCycle").oninput=renderSetupPreview;
 $("#exportData").onclick=download;$("#importData").onchange=function(){var input=this,f=input.files[0];if(!f)return;var reader=new FileReader();reader.onload=function(){try{var d=JSON.parse(reader.result);if(!d||!d.schedule||!Array.isArray(d.schedule.cycle)||!d.schedule.anchor)throw new Error("invalid");if(!confirm("استعادة النسخة ستستبدل بياناتك الحالية. تكمل؟"))return;data=normalize(d);S=data.schedule;save();renderAll();toast("تمت استعادة بياناتك")}catch(e){toast("الملف تالف أو غير صالح")}finally{input.value=""}};reader.readAsText(f)};
 $("#resetApp").onclick=function(){if(!confirm("سيتم حذف جدولك وإجازاتك وإعداداتك من هذا الجهاز. هل أنت متأكد؟"))return;if(!confirm("تأكيد أخير: لا يمكن التراجع إلا من نسخة احتياطية."))return;[KEY,"dawami-cycle-prefs","dawami-github-prefs","dawami-github-schedule","dawami-cycle-overrides"].forEach(function(k){localStorage.removeItem(k)});data=defaults();S=data.schedule;save();buildSetup();open("setupModal");renderAll()};
 $("#installApp").onclick=async function(){if(installPrompt){installPrompt.prompt();var choice=await installPrompt.userChoice;if(choice.outcome==="accepted")toast("تم إرسال دوامي للتثبيت");installPrompt=null}else if(/iphone|ipad|ipod/i.test(navigator.userAgent))toast("من مشاركة Safari اختر: إضافة إلى الشاشة الرئيسية");else toast("التثبيت غير متاح من هذا المتصفح")};
 window.addEventListener("beforeinstallprompt",function(e){e.preventDefault();installPrompt=e;$("#installApp").textContent="تثبيت دوامي الآن"});
 var x=0,y=0;$("#calendarGrid").addEventListener("touchstart",function(e){x=e.changedTouches[0].clientX;y=e.changedTouches[0].clientY},{passive:true});$("#calendarGrid").addEventListener("touchend",function(e){var dx=e.changedTouches[0].clientX-x,dy=e.changedTouches[0].clientY-y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4)moveMonth(dx>0?1:-1)},{passive:true});
 $$(".modal").forEach(function(m){m.addEventListener("click",function(e){if(e.target===m&&m.id!=="setupModal")close(m.id)})});window.addEventListener("keydown",function(e){if(e.key==="Escape"&&$(".modal.open")&&$(".modal.open").id!=="setupModal")close($(".modal.open").id)});window.addEventListener("popstate",function(e){var openModal=$(".modal.open");if(openModal){close(openModal.id,true);return}showPage((e.state&&e.state.dawamiPage)||"calendar",{fromHistory:true,instant:true})})
}
function init(){bind();var initial=location.hash.slice(1)==="settings"?"settings":"calendar";showPage(initial,{replace:true,instant:true});renderAll();setInterval(renderCountdown,1000);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=10.0").catch(function(){});scheduleNotify();if(!data.onboarded){buildSetup();open("setupModal")}}
init();
})();
