(function(){
"use strict";
var C=window.DawamiCore,KEY="dawami-data-v3",BACKUP="dawami-v3-legacy-backup";
var data=loadData(),S=data.schedule,tz=data.settings.timezone||"Asia/Muscat",today=C.dateKeyAt(Date.now(),tz),month=today.slice(0,7)+"-01",page="home",selectedDay=today,setupPattern="14-14",timerTarget=null,notifyTimer=null,holidayStore=read("dawami-oman-holidays-v3")||{years:{}},holidayLoading={};
var months=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
var PALETTES={
 gold:{work:"#FFD45A",workText:"#2B2107",restLight:"#E9EEF5",restLightText:"#344054",restDark:"#080B11",restDarkText:"#F8FAFC"},
 ocean:{work:"#6CC8FF",workText:"#072235",restLight:"#D9EAF7",restLightText:"#16324A",restDark:"#102A43",restDarkText:"#F8FAFC"},
 mint:{work:"#67D7B0",workText:"#08281F",restLight:"#DBF0E8",restLightText:"#173D31",restDark:"#123329",restDarkText:"#F8FAFC"},
 coral:{work:"#FF9B7B",workText:"#3A160D",restLight:"#F4E1DE",restLightText:"#4A2721",restDark:"#3B1F24",restDarkText:"#FFF9F7"},
 lavender:{work:"#B7A1FF",workText:"#211848",restLight:"#E8E3F8",restLightText:"#342A55",restDark:"#241E3B",restDarkText:"#FAF8FF"},
 sand:{work:"#E6C688",workText:"#34260A",restLight:"#ECE6DA",restLightText:"#433928",restDark:"#2C261D",restDarkText:"#FFF9EE"}
};


function $(q,r){return(r||document).querySelector(q)}
function $$(q,r){return Array.prototype.slice.call((r||document).querySelectorAll(q))}
function copy(x){return JSON.parse(JSON.stringify(x))}
function read(k){try{var v=localStorage.getItem(k);return v?JSON.parse(v):null}catch(e){return null}}
function defaults(){return{version:3,onboarded:false,profile:{name:""},settings:{timezone:"Asia/Muscat",theme:"dark",dayStart:"07:00",dayEnd:"19:00",nightStart:"19:00",nightEnd:"07:00",notificationEnabled:false,reminderBefore:60,colorTheme:"gold"},schedule:{anchor:C.dateKeyAt(Date.now(),"Asia/Muscat"),patternId:"14-14",patternName:"14 يوم دوام / 14 يوم إجازة",cycle:copy(C.presets()["14-14"].cycle),overrides:{},leaves:[]},migratedFrom:[]}}
function normalize(d){var base=defaults();d.version=3;d.profile=Object.assign(base.profile,d.profile||{});d.settings=Object.assign(base.settings,d.settings||{});d.schedule=Object.assign(base.schedule,d.schedule||{});d.schedule.cycle=d.schedule.cycle&&d.schedule.cycle.length?d.schedule.cycle:base.schedule.cycle;d.schedule.overrides=d.schedule.overrides||{};d.schedule.leaves=d.schedule.leaves||[];d.migratedFrom=d.migratedFrom||[];return d}
function loadData(){
 var current=read(KEY);if(current&&current.schedule)return normalize(current);
 var d=defaults(),oldP=read("dawami-cycle-prefs")||read("dawami-github-prefs"),oldO=read("dawami-cycle-overrides")||{},oldS=read("dawami-github-schedule");
 if(oldP||oldS||Object.keys(oldO).length){
  if(!localStorage.getItem(BACKUP))try{localStorage.setItem(BACKUP,JSON.stringify({savedAt:new Date().toISOString(),prefs:oldP,changes:oldO,schedule:oldS}))}catch(e){}
  var p=oldP||{},on=Number(p.onDays||p.workDays||14),off=Number(p.offDays||p.restDays||14),work={type:"day",label:"دوام",start:p.shiftStart||"07:00",end:p.shiftEnd||"19:00"};
  d.schedule.anchor=p.anchor||p.startDate||d.schedule.anchor;d.schedule.cycle=C.repeat(work,on).concat(C.repeat({type:"off",label:"إجازة"},off));if(p.anchorPhase==="off")d.schedule.cycle=C.repeat({type:"off",label:"إجازة"},off).concat(C.repeat(work,on));
  d.schedule.patternId=on+"-"+off;d.schedule.patternName=on+" يوم دوام / "+off+" يوم إجازة";d.settings.theme=p.theme||"dark";d.settings.dayStart=work.start;d.settings.dayEnd=work.end;d.profile.name=p.name||"";d.onboarded=true;
  Object.keys(oldO).forEach(function(k){var v=oldO[k];d.schedule.overrides[k]=v==="off"?{type:"off",label:"إجازة"}:v==="work"?copy(work):v});
  var list=Array.isArray(oldS)?oldS:(oldS&&(oldS.days||oldS.entries||oldS.schedule));if(Array.isArray(list))list.forEach(function(x){if(x&&x.date)d.schedule.overrides[x.date.slice(0,10)]={type:mapType(x.type||x.status),label:x.label,start:x.start||x.startTime,end:x.end||x.endTime,note:x.note||""}});
  d.migratedFrom=["النسخة السابقة"];
 }
 d=normalize(d);try{localStorage.setItem(KEY,JSON.stringify(d))}catch(e){}return d
}
function save(msg){try{localStorage.setItem(KEY,JSON.stringify(data));if(msg)toast(msg)}catch(e){toast("ما قدرت أحفظ البيانات")}}
function mapType(v){v=String(v||"").toLowerCase();if(/night|ليل/.test(v))return"night";if(/off|rest|راح|إجاز|اجاز/.test(v))return"off";return"day"}
function add(k,n){return C.addDays(k,n)}
function parts(k){return C.monthKeyParts(k)}
function fmtKey(k,o){if(!k)return"—";return new Intl.DateTimeFormat("ar-OM",Object.assign({timeZone:"UTC",day:"numeric",month:"short"},o||{})).format(new Date(k+"T12:00:00Z"))}
function fmtTime(ms,o){if(!ms)return"—";return new Intl.DateTimeFormat("ar-OM",Object.assign({timeZone:tz,weekday:"long",day:"numeric",month:"long",hour:"numeric",minute:"2-digit"},o||{})).format(new Date(ms))}
function pad(n){return String(Math.max(0,n)).padStart(2,"0")}
function remaining(ms){var m=Math.max(0,Math.floor(ms/60000)),d=Math.floor(m/1440),h=Math.floor((m%1440)/60);return pad(d)+" يوم : "+pad(h)+" ساعة : "+pad(m%60)+" دقيقة"}
function esc(v){return String(v||"").replace(/[&<>"]/g,function(x){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[x]})}
function holidayName(h){var n=String((h&&(h.localName||h.name))||"عطلة رسمية"),e=String((h&&h.name)||n).toLowerCase();if(/[\u0600-\u06ff]/.test(n))return n;if(/fitr/.test(e))return"عيد الفطر";if(/adha/.test(e))return"عيد الأضحى";if(/prophet|mawlid/.test(e))return"المولد النبوي";if(/islamic new year|hijri/.test(e))return"رأس السنة الهجرية";if(/national day/.test(e))return"العيد الوطني";if(/accession|renaissance/.test(e))return"يوم تولّي السلطان";if(/ascension|isra/.test(e))return"الإسراء والمعراج";return n}
function holidayFor(k){var y=holidayStore.years&&holidayStore.years[k.slice(0,4)],list=y&&(y.items||y);return Array.isArray(list)?list.find(function(x){return x.date===k}):null}
async function ensureHolidays(year){var key=String(year),saved=holidayStore.years&&holidayStore.years[key],fresh=saved&&saved.fetchedAt&&Date.now()-saved.fetchedAt<86400000;if(fresh||holidayLoading[key])return;holidayLoading[key]=true;var sync=$("#holidaySync");if(sync)sync.textContent="جاري تحديث عطلات سلطنة عُمان…";try{var url="holidays-om.json?build=20260828-2253",local=await fetch(url,{cache:"reload"});if(!local.ok)throw new Error("holiday file");var bundle=await local.json(),list=bundle.years&&bundle.years[key];if(!Array.isArray(list)||!list.length)throw new Error("holiday year");holidayStore.years=holidayStore.years||{};holidayStore.years[key]={fetchedAt:Date.now(),items:list.map(function(x){return{date:x.date,name:x.name||"",localName:x.localName||""}})};localStorage.setItem("dawami-oman-holidays-v3",JSON.stringify(holidayStore));if(sync)sync.textContent="العطلات الرسمية محدثة • الهجرية حسب الإعلان الرسمي";renderCalendar();renderHome()}catch(e){if(sync)sync.textContent=saved?"نعرض آخر نسخة محفوظة من العطلات":"ستظهر العطلات تلقائيًا عند توفر الاتصال"}finally{delete holidayLoading[key]}}
function textFor(e){if(!e)return"إجازة";var t=e.type;if(t==="night")return"دوام ليلي";if(t==="off")return"إجازة";if(t==="annual")return"إجازة سنوية";if(t==="leave"||t==="comp"||t==="unpaid"||t==="emergency")return"إجازة مسجلة";if(t==="sick")return"مرضية";if(t==="training")return"تدريب";if(t==="overtime")return"إكسترا دي";return"دوام"}
function classFor(e){if(!e)return"off";if(e.type==="night")return"night";if(e.type==="off")return"off";if(e.type==="overtime")return"extra";if(e.type==="training")return"training";if(e.type==="sick")return"sick";if(["annual","leave","comp","unpaid","emergency"].indexOf(e.type)>=0)return"leave";return"work"}
function lastWork(k){for(var i=1;i<500;i++){var d=add(k,-i),ev=C.eventsForDate(S,d).filter(C.isWork);if(ev.length){var e=ev[ev.length-1];return C.interval(d,e,tz)}}return null}
function exactBlock(block){if(!block)return null;var before=lastWork(block.start),next=C.nextShift(S,C.zonedEpoch(block.returnDate,"00:00",tz),tz);return{start:before?before.end:C.zonedEpoch(block.start,"00:00",tz),end:next?next.start:C.zonedEpoch(add(block.end,1),"00:00",tz),next:next}}
function toast(msg){var e=$("#toast");e.textContent=msg;e.classList.add("show");clearTimeout(e._t);e._t=setTimeout(function(){e.classList.remove("show")},1800)}
function open(id){$("#"+id).classList.add("open");document.body.classList.add("modal-open");if(id==="dayModal"&&!(history.state&&history.state.dawamiModal===id))history.pushState({dawamiPage:page,dawamiModal:id},"",location.pathname+location.search+"#"+page+"/day")}
function close(id,fromHistory){$("#"+id).classList.remove("open");if(!$(".modal.open"))document.body.classList.remove("modal-open");if(!fromHistory&&history.state&&history.state.dawamiModal===id)history.back()}

function applyPalette(){var p=PALETTES[data.settings.colorTheme]||PALETTES.gold,dark=data.settings.theme==="dark",root=document.documentElement;root.style.setProperty("--work-color",p.work);root.style.setProperty("--work-text",p.workText);root.style.setProperty("--rest-color",dark?p.restDark:p.restLight);root.style.setProperty("--rest-text",dark?p.restDarkText:p.restLightText);root.style.setProperty("--yellow",p.work);root.style.setProperty("--black",dark?p.restDark:p.restLight)}
function renderAll(){S=data.schedule;tz=data.settings.timezone||"Asia/Muscat";today=C.dateKeyAt(Date.now(),tz);document.documentElement.dataset.theme=data.settings.theme;applyPalette();var meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=data.settings.theme==="dark"?"#070A10":"#F3F6FA";$("#themeBtn").classList.toggle("moon",data.settings.theme!=="dark");$("#themeBtn").setAttribute("aria-label",data.settings.theme==="dark"?"تشغيل الوضع الفاتح":"تشغيل الوضع الداكن");renderHome();renderCalendar();renderSettings()}
function renderHome(){
 var now=Date.now(),state=C.nowStatus(S,now,tz),currentRest=state.kind==="off"||state.kind==="leave",currentBlock=C.restBlock(S,today,currentRest),upcomingFrom=currentRest&&state.nextShift?state.nextShift.date:today,block=C.restBlock(S,upcomingFrom,false),exact=exactBlock(block),card=$("#statusCard"),cyclePos=((C.diffDays(S.anchor,today)%S.cycle.length)+S.cycle.length)%S.cycle.length+1;
 card.className="status "+(state.kind==="work"?"work":state.kind==="upcoming"?"soon":"off");
 if(state.kind==="work"){$("#statusTitle").textContent="أنت مداوم الحين";$("#statusSub").textContent=textFor(state.event)+" من "+state.event.start+" إلى "+state.event.end;$("#countLabel").textContent="باقي على الإجازة";timerTarget=exact&&exact.start}
 else if(currentRest){$("#statusTitle").textContent="أنت في الإجازة";$("#statusSub").textContent="استمتع بوقتك، بنخبرك متى ترجع الدوام";$("#countLabel").textContent="باقي على الدوام";timerTarget=state.nextShift&&state.nextShift.start}
 else{$("#statusTitle").textContent="دوامك يبدأ بعد…";$("#statusSub").textContent=textFor(state.nextShift&&state.nextShift.event)+" الساعة "+((state.nextShift&&state.nextShift.event.start)||"—");$("#countLabel").textContent="باقي على بداية الدوام";timerTarget=state.nextShift&&state.nextShift.start}
 $("#cycleDay").textContent=cyclePos;$("#cycleLength").textContent="من "+S.cycle.length+" يوم";$("#cycleRing").style.setProperty("--p",(cyclePos/S.cycle.length*100)+"%");
 var workLeft=block?C.workDaysBetween(S,today,block.start):0;$("#daysToLeave").textContent=block?workLeft+" يوم":"—";$("#leaveHint").textContent=block?"دوام متبقٍ فعليًا":"ما فيه إجازة قريبة";
 $("#leaveStartShort").textContent=exact?new Intl.DateTimeFormat("ar-OM",{timeZone:tz,day:"numeric",month:"short"}).format(new Date(exact.start)):"—";$("#leaveStartFull").textContent=exact?fmtTime(exact.start,{weekday:"long",hour:"numeric",minute:"2-digit"}):"—";
 $("#returnShort").textContent=exact&&exact.next?new Intl.DateTimeFormat("ar-OM",{timeZone:tz,day:"numeric",month:"short"}).format(new Date(exact.next.start)):"—";$("#returnFull").textContent=exact&&exact.next?fmtTime(exact.next.start,{weekday:"long",hour:"numeric",minute:"2-digit"}):"—";var tp=parts(today),monthly=C.monthStats(S,tp.year,tp.month);$("#monthWorkDays").textContent=monthly.workDays+" يوم";$("#monthWorkHint").textContent=months[tp.month-1]+" • محسوب من جدولك";
 renderCountdown();var strip=$("#nextStrip");strip.innerHTML="";for(var i=0;i<7;i++){var k=add(today,i),e=C.primaryEvent(S,k),holiday=holidayFor(k),b=document.createElement("button");b.className="strip-day "+classFor(e)+(i===0?" today":"")+(holiday?" official":"");b.innerHTML="<small>"+fmtKey(k,{weekday:"short"})+"</small><b>"+Number(k.slice(8))+"</b><span>"+textFor(e)+"</span>"+(holiday?'<small class="official-name">'+esc(holidayName(holiday))+"</small>":"");b.onclick=(function(x){return function(){showDay(x)}})(k);strip.appendChild(b)}ensureHolidays(Number(today.slice(0,4)))
}
function renderCountdown(){var box=$("#countdown");if(timerTarget){var m=Math.max(0,Math.floor((timerTarget-Date.now())/60000)),d=Math.floor(m/1440),hr=Math.floor((m%1440)/60),min=m%60;box.className="countdown-parts";box.innerHTML="<span><b>"+pad(d)+"</b><small>يوم</small></span><i>:</i><span><b>"+pad(hr)+"</b><small>ساعة</small></span><i>:</i><span><b>"+pad(min)+"</b><small>دقيقة</small></span>"}else{box.className="countdown-parts empty";box.textContent="ما فيه موعد قريب"}if(timerTarget&&Date.now()>timerTarget)renderHome()}
function renderCalendar(){
 var p=parts(month);$("#monthLabel").textContent=months[p.month-1]+" "+p.year;var first=p.year+"-"+String(p.month).padStart(2,"0")+"-01",offset=(new Date(first+"T12:00:00Z").getUTCDay()+6)%7,start=add(first,-offset),grid=$("#calendarGrid");grid.innerHTML="";
 for(var i=0;i<42;i++){var k=add(start,i),e=C.primaryEvent(S,k),holiday=holidayFor(k),b=document.createElement("button"),outside=parts(k).month!==p.month;b.className="day "+classFor(e)+(outside?" out":"")+(k===today?" today":"")+(S.overrides[k]!==undefined?" manual":"")+(e.note?" has-note":"")+(holiday?" official":"");b.innerHTML="<em>"+Number(k.slice(8))+"</em><b>"+textFor(e)+"</b>"+(holiday?'<small class="official-name">'+esc(holidayName(holiday))+"</small>":"");b.onclick=(function(x){return function(){showDay(x)}})(k);grid.appendChild(b)}
 ensureHolidays(p.year)
}
function showDay(k){selectedDay=k;var events=C.eventsForDate(S,k),e=events[0]||{type:"off"},holiday=holidayFor(k),special=["overtime","annual","sick","training"],bits=[];$("#selectedDate").textContent=fmtKey(k,{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("#selectedStatus").textContent=(holiday?holidayName(holiday)+" • ":"")+events.map(textFor).join("، ");if(holiday)bits.push("عطلة رسمية في سلطنة عُمان");if(C.isWork(e)&&e.start&&e.end)bits.push("من "+e.start+" إلى "+e.end);if(e.job||e.location)bits.push("الموقع: "+(e.job||e.location));if(e.note)bits.push(e.note);$("#selectedTime").textContent=bits.join(" • ")||"ما عندك إضافة على هذا اليوم";$("#dayType").value=special.indexOf(e.type)>=0?e.type:"overtime";$("#dayStart").value=e.start||data.settings.dayStart;$("#dayEnd").value=e.end||data.settings.dayEnd;$("#dayJob").value=e.job||e.location||"";$("#dayNote").value=e.note||"";selectDayType($("#dayType").value);$("#toggleEditDay").textContent=S.overrides[k]!==undefined?"تعديل الإضافة":"أضف على هذا اليوم";$("#editDay").hidden=true;open("dayModal")}
function selectDayType(type){$("#dayType").value=type;var timed=type==="overtime"||type==="training";$("#dayTimes").hidden=!timed;if(timed&&!$("#dayStart").value){$("#dayStart").value=data.settings.dayStart;$("#dayEnd").value=data.settings.dayEnd}$$("[data-day-type]").forEach(function(b){b.classList.toggle("active",b.dataset.dayType===type)})}
function moveMonth(n){var p=parts(month),d=new Date(Date.UTC(p.year,p.month-1+n,1));month=d.getUTCFullYear()+"-"+String(d.getUTCMonth()+1).padStart(2,"0")+"-01";renderCalendar()}
function reminderLabel(min){min=Number(min)||60;if(min===30)return"30 دقيقة";if(min===60)return"ساعة";if(min===120)return"ساعتين";if(min===720)return"12 ساعة";if(min===1440)return"يوم";return min+" دقيقة"}
function renderSettings(){
 var id=C.presets()[S.patternId]?S.patternId:"14-14";$("#settingsName").value=data.profile.name||"";$("#timezoneSelect").value=data.settings.timezone||"Asia/Muscat";$("#reminderBefore").value=String(data.settings.reminderBefore||60);$("#patternSelect").value=id;$("#anchorDate").value=S.anchor;$("#workStart").value=data.settings.dayStart;$("#workEnd").value=data.settings.dayEnd;$("#nightStart").value=data.settings.nightStart;$("#nightEnd").value=data.settings.nightEnd;$("#nightTimes").hidden=id!=="2d2n4";toggleSwitch("darkSwitch",data.settings.theme==="dark");toggleSwitch("notifySwitch",data.settings.notificationEnabled);$("#notifyText").textContent=data.settings.notificationEnabled?"مفعل قبل الدوام بـ"+reminderLabel(data.settings.reminderBefore):"غير مفعل";$("#reminderBefore").disabled=!data.settings.notificationEnabled;document.querySelectorAll("[data-palette]").forEach(function(b){var active=b.dataset.palette===(data.settings.colorTheme||"gold");b.classList.toggle("active",active);b.setAttribute("aria-pressed",active?"true":"false")});renderCyclePreview()
}
function renderCyclePreview(){var box=$("#cyclePreview");box.innerHTML=S.cycle.map(function(e){return'<i class="'+classFor(C.normalizeEvent(e))+'"></i>'}).join("")}
function toggleSwitch(id,on){$("#"+id).classList.toggle("on",!!on)}
function applyTimes(cycle){return cycle.map(function(e){e=copy(e);if(e.type==="day"||e.type==="work"){e.label="دوام";e.start=data.settings.dayStart;e.end=data.settings.dayEnd}if(e.type==="night"){e.label="دوام ليلي";e.start=data.settings.nightStart;e.end=data.settings.nightEnd}if(e.type==="off")e.label="إجازة";return e})}
function patternName(id){var names={"14-14":"14 يوم دوام / 14 يوم إجازة","28-14":"28 يوم دوام / 14 يوم إجازة","7-7":"7 أيام دوام / 7 أيام إجازة","4-4":"4 أيام دوام / 4 أيام إجازة","2d2n4":"يومان نهاري / يومان ليلي / 4 أيام إجازة"};return names[id]||names["14-14"]}
function savePattern(){
 var id=$("#patternSelect").value,anchor=$("#anchorDate").value;if(!anchor){toast("حدد أول يوم في دورة الدوام");return}data.profile.name=$("#settingsName").value.trim();data.settings.timezone=$("#timezoneSelect").value||"Asia/Muscat";data.settings.reminderBefore=Number($("#reminderBefore").value)||60;data.settings.dayStart=$("#workStart").value||"07:00";data.settings.dayEnd=$("#workEnd").value||"19:00";data.settings.nightStart=$("#nightStart").value||"19:00";data.settings.nightEnd=$("#nightEnd").value||"07:00";S.anchor=anchor;S.patternId=id;S.patternName=patternName(id);S.cycle=applyTimes(copy(C.presets()[id].cycle));save("تم حفظ نمط دوامك");renderAll();showPage("home")
}
function showPage(id,opts){if(!$("#"+id))id="home";page=id;$$(".page").forEach(function(x){x.classList.toggle("active",x.id===id)});$$("[data-page]").forEach(function(x){x.classList.toggle("active",x.dataset.page===id)});window.scrollTo({top:0,behavior:"auto"});if(!(opts&&opts.fromHistory)){var next=location.pathname+location.search+"#"+id;if(opts&&opts.replace)history.replaceState({dawamiPage:id},"",next);else if(!(history.state&&history.state.dawamiPage===id&&!history.state.dawamiModal))history.pushState({dawamiPage:id},"",next)}if(id==="calendar")renderCalendar();if(id==="settings")renderSettings()}
function buildSetup(){
 var ids=["14-14","28-14","7-7","4-4","2d2n4"],box=$("#setupPatterns");box.innerHTML=ids.map(function(id){return'<button class="pattern" data-setup-pattern="'+id+'">'+patternName(id)+"</button>"}).join("");$$("[data-setup-pattern]",box).forEach(function(b){b.onclick=function(){setupPattern=b.dataset.setupPattern;$$("[data-setup-pattern]",box).forEach(function(x){x.classList.toggle("active",x===b)});renderSetupPreview()}});setupPattern=C.presets()[S.patternId]?S.patternId:"14-14";var active=$('[data-setup-pattern="'+setupPattern+'"]',box);if(active)active.classList.add("active");$("#setupName").value=data.profile.name||"";$("#setupAnchor").value=S.anchor||today;$("#setupStart").value=data.settings.dayStart;$("#setupEnd").value=data.settings.dayEnd;renderSetupPreview()
}
function renderSetupPreview(){var cyc=C.presets()[setupPattern].cycle,box=$("#setupPreview");box.innerHTML="";for(var i=0;i<28;i++){var e=C.normalizeEvent(cyc[i%cyc.length]),x=document.createElement("i");x.className=classFor(e);box.appendChild(x)}}
function finishSetup(){var anchor=$("#setupAnchor").value;if(!anchor){toast("حدد أول يوم دوام");return}data.profile.name=$("#setupName").value.trim();data.settings.dayStart=$("#setupStart").value||"07:00";data.settings.dayEnd=$("#setupEnd").value||"19:00";S.anchor=anchor;S.patternId=setupPattern;S.patternName=patternName(setupPattern);S.cycle=applyTimes(copy(C.presets()[setupPattern].cycle));data.onboarded=true;save();close("setupModal");renderAll();toast("تمام، حسبنا دوامك وإجازتك")}
async function toggleNotify(){
 if(data.settings.notificationEnabled){data.settings.notificationEnabled=false;clearTimeout(notifyTimer);save();renderSettings();toast("تم إيقاف التنبيه");return}
 if(!("Notification"in window)||!("serviceWorker"in navigator)){toast("التنبيه غير مدعوم في هذا المتصفح");return}var result=Notification.permission;if(result==="default")result=await Notification.requestPermission();if(result!=="granted"){toast("ما تم السماح بالتنبيه");return}data.settings.notificationEnabled=true;save();renderSettings();scheduleNotify();toast("تم تفعيل التنبيه داخل التطبيق")
}
function scheduleNotify(){clearTimeout(notifyTimer);if(!data.settings.notificationEnabled||!("Notification"in window)||Notification.permission!=="granted")return;var before=Number(data.settings.reminderBefore)||60,next=C.nextShift(S,Date.now(),tz),at=next&&next.start-before*60000-Date.now();if(at>0&&at<2147483647)notifyTimer=setTimeout(async function(){try{var reg=await navigator.serviceWorker.ready;reg.showNotification("دوامك بعد "+reminderLabel(before),{body:textFor(next.event)+" يبدأ "+fmtTime(next.start),icon:"icon.svg",tag:"dawami"})}catch(e){}scheduleNotify()},at)}
async function forceSiteUpdate(){try{toast("جاري تحديث الموقع…");if("serviceWorker"in navigator){var regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(function(r){return r.unregister()}))}if("caches"in window){var keys=await caches.keys();await Promise.all(keys.map(function(k){return caches.delete(k)}))}setTimeout(function(){location.replace(location.pathname+"?fresh=6.0#"+page)},350)}catch(e){location.reload()}}
function download(){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="dawami-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(function(){URL.revokeObjectURL(url)},500)}
function bind(){
 $$("[data-page]").forEach(function(b){b.onclick=function(){showPage(b.dataset.page)}});$$("[data-open-page]").forEach(function(b){b.onclick=function(){showPage(b.dataset.openPage)}});$$("[data-close]").forEach(function(b){b.onclick=function(){close(b.dataset.close)}});
 $("#themeBtn").onclick=function(){data.settings.theme=data.settings.theme==="dark"?"light":"dark";save();renderAll()};$("#darkSwitch").onclick=$("#themeBtn").onclick;
 $("#nextMonth").onclick=function(){moveMonth(1)};$("#prevMonth").onclick=function(){moveMonth(-1)};$("#goToday").onclick=function(){month=today.slice(0,7)+"-01";renderCalendar()};
 document.querySelectorAll("[data-palette]").forEach(function(b){b.onclick=function(){data.settings.colorTheme=b.dataset.palette;save();renderAll();toast("تم تغيير ألوان جدولك")}});$("#patternSelect").onchange=function(){$("#nightTimes").hidden=this.value!=="2d2n4";var temp=copy(C.presets()[this.value].cycle);$("#cyclePreview").innerHTML=temp.map(function(e){return'<i class="'+classFor(C.normalizeEvent(e))+'"></i>'}).join("")};$("#saveSettings").onclick=savePattern;$("#notifySwitch").onclick=toggleNotify;$("#reminderBefore").onchange=function(){data.settings.reminderBefore=Number(this.value)||60;save();renderSettings();scheduleNotify();toast("تم تغيير وقت التنبيه")};$("#forceUpdate").onclick=forceSiteUpdate;
 $("#toggleEditDay").onclick=function(){$("#editDay").hidden=!$("#editDay").hidden;if(!$("#editDay").hidden)setTimeout(function(){$("#editDay").scrollIntoView({behavior:"smooth",block:"start"})},80)};$$("[data-day-type]").forEach(function(b){b.onclick=function(){selectDayType(b.dataset.dayType)}});$("#dayType").onchange=function(){selectDayType(this.value)};
 $("#saveDay").onclick=function(){var type=$("#dayType").value,timed=type==="overtime"||type==="training";S.overrides[selectedDay]={type:type,label:textFor({type:type}),start:timed?($("#dayStart").value||data.settings.dayStart):"",end:timed?($("#dayEnd").value||data.settings.dayEnd):"",job:$("#dayJob").value.trim(),note:$("#dayNote").value.trim()};save();close("dayModal");renderAll();toast("تم حفظ اليوم وتلوينه")};$("#resetDay").onclick=function(){delete S.overrides[selectedDay];save();close("dayModal");renderAll();toast("رجع اليوم لجدولك")};
 $("#showSetup").onclick=function(){buildSetup();open("setupModal")};$("#finishSetup").onclick=finishSetup;$("#exportData").onclick=download;$("#importData").onchange=function(){var f=this.files[0];if(!f)return;var reader=new FileReader();reader.onload=function(){try{var d=JSON.parse(reader.result);if(!d.schedule){toast("الملف غير صحيح");return}data=normalize(d);S=data.schedule;save();renderAll();toast("تمت استعادة بياناتك")}catch(e){toast("الملف غير صحيح")}};reader.readAsText(f)};
 var x=0;$("#calendarGrid").addEventListener("touchstart",function(e){x=e.changedTouches[0].clientX},{passive:true});$("#calendarGrid").addEventListener("touchend",function(e){var diff=e.changedTouches[0].clientX-x;if(Math.abs(diff)>55)moveMonth(diff>0?1:-1)},{passive:true});$$(".modal").forEach(function(m){m.addEventListener("click",function(e){if(e.target===m&&m.id!=="setupModal")close(m.id)})});var sy=0;$(".sheet-head").addEventListener("touchstart",function(e){sy=e.changedTouches[0].clientY},{passive:true});$(".sheet-head").addEventListener("touchend",function(e){if(e.changedTouches[0].clientY-sy>70)close("dayModal")},{passive:true});window.addEventListener("keydown",function(e){if(e.key==="Escape"&&$(".modal.open")&&$(".modal.open").id!=="setupModal")close($(".modal.open").id)});window.addEventListener("popstate",function(e){var openModal=$(".modal.open");if(openModal){close(openModal.id,true);return}showPage((e.state&&e.state.dawamiPage)||"home",{fromHistory:true,instant:true})})
}
function init(){bind();var initial=["home","calendar","settings"].indexOf(location.hash.slice(1))>=0?location.hash.slice(1):"home";showPage(initial,{replace:true,instant:true});renderAll();setInterval(renderCountdown,1000);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=7.0").catch(function(){});scheduleNotify();if(!data.onboarded){buildSetup();open("setupModal")}}
init();
})();