import fs from "node:fs";
import assert from "node:assert/strict";

const html=fs.readFileSync("index.html","utf8");
const sw=fs.readFileSync("sw.js","utf8");
for(const file of ["manifest.webmanifest","sw.js","icon.svg"])assert.ok(fs.existsSync(file),file+" is missing");
assert.doesNotThrow(()=>new Function(sw),"sw.js must parse");
assert.ok(html.includes('data-build="9.3-inline"'));
assert.equal(html.includes('dawami-v9-1.css?v=9.1'),false);
assert.equal(html.includes('dawami-v9-1.js?v=9.1'),false);

const style=html.match(/<style data-inline="dawami-v9\.3">([\s\S]*?)<\/style>/);
assert.ok(style&&style[1].length>25000,"complete design CSS must be inlined");
const scripts=[...html.matchAll(/<script data-inline="[^"]+">([\s\S]*?)<\/script>/g)].map(m=>m[1]);
assert.equal(scripts.length,2);
scripts.forEach((code,i)=>assert.doesNotThrow(()=>new Function(code),"inline script "+i+" must parse"));
const app=scripts[1];
assert.ok(app.indexOf("var DEFAULT_COLORS=")<app.indexOf("var data=loadData()"),"color defaults must exist before loading saved data");
assert.ok(app.includes('location.hash.slice(1)==="settings"?"settings":"calendar"'),"calendar must always be the first screen");
assert.ok(app.includes("function $$(q,r)"),"list selector helper must exist");
assert.ok(app.includes('$$(".page").forEach'),"page lists must use $$");
assert.ok(app.includes('$$("[data-page]").forEach'),"data lists must use $$");

const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
const refs=[...app.matchAll(/\$\("#([A-Za-z][A-Za-z0-9_-]*)"\)/g)].map(m=>m[1]);
assert.deepEqual([...new Set(refs.filter(id=>!ids.has(id)))],[]);
const markup=html.replace(/<script[\s\S]*?<\/script>/g,"");
assert.equal(markup.includes("وردية"),false);
assert.equal(app.includes("وردية"),false);
assert.equal(html.includes('class="bottom-nav"'),false);
assert.ok(html.includes('class="page active app-panel calendar-panel" id="calendar"'));
assert.ok(html.includes('class="today-button status-launch"'));
assert.ok(html.includes('class="dashboard-sheet"'));
assert.ok(html.includes('class="settings-card color-studio"'));
assert.equal((html.match(/data-color-key=/g)||[]).length,8);
assert.equal((html.match(/data-palette=/g)||[]).length,5);
assert.ok(app.includes('"dawami-cycle-prefs"'));
assert.ok(app.includes('"dawami-github-schedule"'));
const manifest=JSON.parse(fs.readFileSync("manifest.webmanifest","utf8"));
assert.equal(manifest.dir,"rtl");
console.log("Dawami 9.3 inline build: all tests passed");
