import fs from "node:fs";
import assert from "node:assert/strict";
const html=fs.readFileSync("index.html","utf8");
const app=fs.readFileSync("app.js","utf8");
const core=fs.readFileSync("core.js","utf8");
for(const file of ["styles.css","manifest.webmanifest","sw.js","icon.svg"])assert.ok(fs.existsSync(file),file+" is missing");
assert.doesNotThrow(()=>new Function(core),"core.js must parse");
assert.doesNotThrow(()=>new Function(app),"app.js must parse");
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
const direct=[...app.matchAll(/\$\("#([A-Za-z][A-Za-z0-9_-]*)"\)/g)].map(m=>m[1]);
const textRefs=[...app.matchAll(/setText\("([A-Za-z][A-Za-z0-9_-]*)"/g)].map(m=>m[1]);
const missing=[...new Set([...direct,...textRefs].filter(id=>!ids.has(id)))];
assert.deepEqual(missing,[],"Missing DOM IDs: "+missing.join(", "));
const manifest=JSON.parse(fs.readFileSync("manifest.webmanifest","utf8"));
assert.equal(manifest.dir,"rtl");
assert.ok(html.includes('dir="rtl"'));
assert.ok(html.includes('dawami-github-schedule')===false,"Legacy keys belong in migration code, not markup");
assert.ok(app.includes('"dawami-github-schedule"'));
assert.ok(app.includes('"dawami-github-prefs"'));
console.log("Dawami UI smoke tests: all tests passed");