import fs from "node:fs";
import assert from "node:assert/strict";
const html=fs.readFileSync("index.html","utf8");
const app=fs.readFileSync("simple.js","utf8");
const core=fs.readFileSync("core.js","utf8");
for(const file of ["simple.css","manifest.webmanifest","sw.js","icon.svg"])assert.ok(fs.existsSync(file),file+" is missing");
assert.doesNotThrow(()=>new Function(core),"core.js must parse");
assert.doesNotThrow(()=>new Function(app),"simple.js must parse");
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
const refs=[...app.matchAll(/\$\("#([A-Za-z][A-Za-z0-9_-]*)"\)/g)].map(m=>m[1]);
assert.deepEqual([...new Set(refs.filter(id=>!ids.has(id)))],[]);
assert.equal(html.includes("وردية"),false);
assert.equal(app.includes("وردية"),false);
assert.equal(html.match(/data-page=/g).length,3);
assert.ok(app.includes('"dawami-cycle-prefs"'));
assert.ok(app.includes('"dawami-github-schedule"'));
const manifest=JSON.parse(fs.readFileSync("manifest.webmanifest","utf8"));
assert.equal(manifest.dir,"rtl");
console.log("Dawami simple UI: all tests passed");